// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConfigSystemBannerMessage {
    /**
     * @return Whether or not the banner message is closable.
     * 
     */
    private @Nullable Boolean closable;
    /**
     * @return The date the banner message will start displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    private @Nullable String fromDate;
    /**
     * @return The message to display in the banner.
     * 
     */
    private String message;
    /**
     * @return The date the banner message will stop displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    private @Nullable String toDate;
    /**
     * @return The type of banner message. Can be `&#34;info&#34;`, `&#34;warning&#34;`, `&#34;success&#34;` or `&#34;danger&#34;`.
     * 
     */
    private @Nullable String type;

    private ConfigSystemBannerMessage() {}
    /**
     * @return Whether or not the banner message is closable.
     * 
     */
    public Optional<Boolean> closable() {
        return Optional.ofNullable(this.closable);
    }
    /**
     * @return The date the banner message will start displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    public Optional<String> fromDate() {
        return Optional.ofNullable(this.fromDate);
    }
    /**
     * @return The message to display in the banner.
     * 
     */
    public String message() {
        return this.message;
    }
    /**
     * @return The date the banner message will stop displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    public Optional<String> toDate() {
        return Optional.ofNullable(this.toDate);
    }
    /**
     * @return The type of banner message. Can be `&#34;info&#34;`, `&#34;warning&#34;`, `&#34;success&#34;` or `&#34;danger&#34;`.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConfigSystemBannerMessage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean closable;
        private @Nullable String fromDate;
        private String message;
        private @Nullable String toDate;
        private @Nullable String type;
        public Builder() {}
        public Builder(ConfigSystemBannerMessage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.closable = defaults.closable;
    	      this.fromDate = defaults.fromDate;
    	      this.message = defaults.message;
    	      this.toDate = defaults.toDate;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder closable(@Nullable Boolean closable) {

            this.closable = closable;
            return this;
        }
        @CustomType.Setter
        public Builder fromDate(@Nullable String fromDate) {

            this.fromDate = fromDate;
            return this;
        }
        @CustomType.Setter
        public Builder message(String message) {
            if (message == null) {
              throw new MissingRequiredPropertyException("ConfigSystemBannerMessage", "message");
            }
            this.message = message;
            return this;
        }
        @CustomType.Setter
        public Builder toDate(@Nullable String toDate) {

            this.toDate = toDate;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        public ConfigSystemBannerMessage build() {
            final var _resultValue = new ConfigSystemBannerMessage();
            _resultValue.closable = closable;
            _resultValue.fromDate = fromDate;
            _resultValue.message = message;
            _resultValue.toDate = toDate;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
