// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.harbor.outputs.GetGroupsGroup;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetGroupsResult {
    /**
     * @return The name of the group to filter by.
     * 
     */
    private @Nullable String groupName;
    private List<GetGroupsGroup> groups;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The LDAP group DN to filter by.
     * 
     */
    private @Nullable String ldapGroupDn;

    private GetGroupsResult() {}
    /**
     * @return The name of the group to filter by.
     * 
     */
    public Optional<String> groupName() {
        return Optional.ofNullable(this.groupName);
    }
    public List<GetGroupsGroup> groups() {
        return this.groups;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The LDAP group DN to filter by.
     * 
     */
    public Optional<String> ldapGroupDn() {
        return Optional.ofNullable(this.ldapGroupDn);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGroupsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String groupName;
        private List<GetGroupsGroup> groups;
        private String id;
        private @Nullable String ldapGroupDn;
        public Builder() {}
        public Builder(GetGroupsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.groupName = defaults.groupName;
    	      this.groups = defaults.groups;
    	      this.id = defaults.id;
    	      this.ldapGroupDn = defaults.ldapGroupDn;
        }

        @CustomType.Setter
        public Builder groupName(@Nullable String groupName) {

            this.groupName = groupName;
            return this;
        }
        @CustomType.Setter
        public Builder groups(List<GetGroupsGroup> groups) {
            if (groups == null) {
              throw new MissingRequiredPropertyException("GetGroupsResult", "groups");
            }
            this.groups = groups;
            return this;
        }
        public Builder groups(GetGroupsGroup... groups) {
            return groups(List.of(groups));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetGroupsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ldapGroupDn(@Nullable String ldapGroupDn) {

            this.ldapGroupDn = ldapGroupDn;
            return this;
        }
        public GetGroupsResult build() {
            final var _resultValue = new GetGroupsResult();
            _resultValue.groupName = groupName;
            _resultValue.groups = groups;
            _resultValue.id = id;
            _resultValue.ldapGroupDn = ldapGroupDn;
            return _resultValue;
        }
    }
}
