// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.harbor.outputs.GetProjectMemberUsersProjectMemberUser;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetProjectMemberUsersResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The id of the project within harbor.
     * 
     */
    private String projectId;
    private List<GetProjectMemberUsersProjectMemberUser> projectMemberUsers;

    private GetProjectMemberUsersResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The id of the project within harbor.
     * 
     */
    public String projectId() {
        return this.projectId;
    }
    public List<GetProjectMemberUsersProjectMemberUser> projectMemberUsers() {
        return this.projectMemberUsers;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetProjectMemberUsersResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String projectId;
        private List<GetProjectMemberUsersProjectMemberUser> projectMemberUsers;
        public Builder() {}
        public Builder(GetProjectMemberUsersResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.projectId = defaults.projectId;
    	      this.projectMemberUsers = defaults.projectMemberUsers;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberUsersResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberUsersResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder projectMemberUsers(List<GetProjectMemberUsersProjectMemberUser> projectMemberUsers) {
            if (projectMemberUsers == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberUsersResult", "projectMemberUsers");
            }
            this.projectMemberUsers = projectMemberUsers;
            return this;
        }
        public Builder projectMemberUsers(GetProjectMemberUsersProjectMemberUser... projectMemberUsers) {
            return projectMemberUsers(List.of(projectMemberUsers));
        }
        public GetProjectMemberUsersResult build() {
            final var _resultValue = new GetProjectMemberUsersResult();
            _resultValue.id = id;
            _resultValue.projectId = projectId;
            _resultValue.projectMemberUsers = projectMemberUsers;
            return _resultValue;
        }
    }
}
