// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetProjectMemberGroupsProjectMemberGroup {
    private String groupName;
    /**
     * @return The ID of this resource.
     * 
     */
    private String id;
    /**
     * @return The id of the project within harbor.
     * 
     */
    private String projectId;
    private String role;

    private GetProjectMemberGroupsProjectMemberGroup() {}
    public String groupName() {
        return this.groupName;
    }
    /**
     * @return The ID of this resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The id of the project within harbor.
     * 
     */
    public String projectId() {
        return this.projectId;
    }
    public String role() {
        return this.role;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetProjectMemberGroupsProjectMemberGroup defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String groupName;
        private String id;
        private String projectId;
        private String role;
        public Builder() {}
        public Builder(GetProjectMemberGroupsProjectMemberGroup defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.groupName = defaults.groupName;
    	      this.id = defaults.id;
    	      this.projectId = defaults.projectId;
    	      this.role = defaults.role;
        }

        @CustomType.Setter
        public Builder groupName(String groupName) {
            if (groupName == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsProjectMemberGroup", "groupName");
            }
            this.groupName = groupName;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsProjectMemberGroup", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsProjectMemberGroup", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsProjectMemberGroup", "role");
            }
            this.role = role;
            return this;
        }
        public GetProjectMemberGroupsProjectMemberGroup build() {
            final var _resultValue = new GetProjectMemberGroupsProjectMemberGroup();
            _resultValue.groupName = groupName;
            _resultValue.id = id;
            _resultValue.projectId = projectId;
            _resultValue.role = role;
            return _resultValue;
        }
    }
}
