// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumiverse.harbor.outputs.GetProjectMemberGroupsProjectMemberGroup;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetProjectMemberGroupsResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The id of the project within harbor.
     * 
     */
    private String projectId;
    private List<GetProjectMemberGroupsProjectMemberGroup> projectMemberGroups;

    private GetProjectMemberGroupsResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The id of the project within harbor.
     * 
     */
    public String projectId() {
        return this.projectId;
    }
    public List<GetProjectMemberGroupsProjectMemberGroup> projectMemberGroups() {
        return this.projectMemberGroups;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetProjectMemberGroupsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String projectId;
        private List<GetProjectMemberGroupsProjectMemberGroup> projectMemberGroups;
        public Builder() {}
        public Builder(GetProjectMemberGroupsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.projectId = defaults.projectId;
    	      this.projectMemberGroups = defaults.projectMemberGroups;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder projectMemberGroups(List<GetProjectMemberGroupsProjectMemberGroup> projectMemberGroups) {
            if (projectMemberGroups == null) {
              throw new MissingRequiredPropertyException("GetProjectMemberGroupsResult", "projectMemberGroups");
            }
            this.projectMemberGroups = projectMemberGroups;
            return this;
        }
        public Builder projectMemberGroups(GetProjectMemberGroupsProjectMemberGroup... projectMemberGroups) {
            return projectMemberGroups(List.of(projectMemberGroups));
        }
        public GetProjectMemberGroupsResult build() {
            final var _resultValue = new GetProjectMemberGroupsResult();
            _resultValue.id = id;
            _resultValue.projectId = projectId;
            _resultValue.projectMemberGroups = projectMemberGroups;
            return _resultValue;
        }
    }
}
