// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetUsersUser {
    private Boolean admin;
    private String comment;
    /**
     * @return The email of the user to filter by.
     * 
     */
    private String email;
    private String fullName;
    /**
     * @return The ID of this resource.
     * 
     */
    private String id;
    /**
     * @return The name of the user to filter by.
     * 
     */
    private String username;

    private GetUsersUser() {}
    public Boolean admin() {
        return this.admin;
    }
    public String comment() {
        return this.comment;
    }
    /**
     * @return The email of the user to filter by.
     * 
     */
    public String email() {
        return this.email;
    }
    public String fullName() {
        return this.fullName;
    }
    /**
     * @return The ID of this resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The name of the user to filter by.
     * 
     */
    public String username() {
        return this.username;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetUsersUser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean admin;
        private String comment;
        private String email;
        private String fullName;
        private String id;
        private String username;
        public Builder() {}
        public Builder(GetUsersUser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.admin = defaults.admin;
    	      this.comment = defaults.comment;
    	      this.email = defaults.email;
    	      this.fullName = defaults.fullName;
    	      this.id = defaults.id;
    	      this.username = defaults.username;
        }

        @CustomType.Setter
        public Builder admin(Boolean admin) {
            if (admin == null) {
              throw new MissingRequiredPropertyException("GetUsersUser", "admin");
            }
            this.admin = admin;
            return this;
        }
        @CustomType.Setter
        public Builder comment(String comment) {
            if (comment == null) {
              throw new MissingRequiredPropertyException("GetUsersUser", "comment");
            }
            this.comment = comment;
            return this;
        }
        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("GetUsersUser", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder fullName(String fullName) {
            if (fullName == null) {
              throw new MissingRequiredPropertyException("GetUsersUser", "fullName");
            }
            this.fullName = fullName;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetUsersUser", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder username(String username) {
            if (username == null) {
              throw new MissingRequiredPropertyException("GetUsersUser", "username");
            }
            this.username = username;
            return this;
        }
        public GetUsersUser build() {
            final var _resultValue = new GetUsersUser();
            _resultValue.admin = admin;
            _resultValue.comment = comment;
            _resultValue.email = email;
            _resultValue.fullName = fullName;
            _resultValue.id = id;
            _resultValue.username = username;
            return _resultValue;
        }
    }
}
