// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.GarbageCollectionArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.GarbageCollectionState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 */
@ResourceType(type="harbor:index/garbageCollection:GarbageCollection")
public class GarbageCollection extends com.pulumi.resources.CustomResource {
    /**
     * Allow garbage collection on untagged artifacts.
     * 
     */
    @Export(name="deleteUntagged", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> deleteUntagged;

    /**
     * @return Allow garbage collection on untagged artifacts.
     * 
     */
    public Output<Optional<Boolean>> deleteUntagged() {
        return Codegen.optional(this.deleteUntagged);
    }
    /**
     * Sets the schedule how often the Garbage Collection will run.  Can be to `&#34;hourly&#34;`, `&#34;daily&#34;`, `&#34;weekly&#34;` or can be a custom cron string ie, `&#34;0 5 4 * * *&#34;`
     * 
     */
    @Export(name="schedule", refs={String.class}, tree="[0]")
    private Output<String> schedule;

    /**
     * @return Sets the schedule how often the Garbage Collection will run.  Can be to `&#34;hourly&#34;`, `&#34;daily&#34;`, `&#34;weekly&#34;` or can be a custom cron string ie, `&#34;0 5 4 * * *&#34;`
     * 
     */
    public Output<String> schedule() {
        return this.schedule;
    }
    /**
     * Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
     * 
     */
    @Export(name="workers", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> workers;

    /**
     * @return Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
     * 
     */
    public Output<Optional<Integer>> workers() {
        return Codegen.optional(this.workers);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GarbageCollection(java.lang.String name) {
        this(name, GarbageCollectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GarbageCollection(java.lang.String name, GarbageCollectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GarbageCollection(java.lang.String name, GarbageCollectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/garbageCollection:GarbageCollection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private GarbageCollection(java.lang.String name, Output<java.lang.String> id, @Nullable GarbageCollectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/garbageCollection:GarbageCollection", name, state, makeResourceOptions(options, id), false);
    }

    private static GarbageCollectionArgs makeArgs(GarbageCollectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? GarbageCollectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-harbor")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GarbageCollection get(java.lang.String name, Output<java.lang.String> id, @Nullable GarbageCollectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GarbageCollection(name, id, state, options);
    }
}
