// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GroupArgs extends com.pulumi.resources.ResourceArgs {

    public static final GroupArgs Empty = new GroupArgs();

    @Import(name="groupName", required=true)
    private Output<String> groupName;

    public Output<String> groupName() {
        return this.groupName;
    }

    @Import(name="groupType", required=true)
    private Output<Integer> groupType;

    public Output<Integer> groupType() {
        return this.groupType;
    }

    @Import(name="ldapGroupDn")
    private @Nullable Output<String> ldapGroupDn;

    public Optional<Output<String>> ldapGroupDn() {
        return Optional.ofNullable(this.ldapGroupDn);
    }

    private GroupArgs() {}

    private GroupArgs(GroupArgs $) {
        this.groupName = $.groupName;
        this.groupType = $.groupType;
        this.ldapGroupDn = $.ldapGroupDn;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GroupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GroupArgs $;

        public Builder() {
            $ = new GroupArgs();
        }

        public Builder(GroupArgs defaults) {
            $ = new GroupArgs(Objects.requireNonNull(defaults));
        }

        public Builder groupName(Output<String> groupName) {
            $.groupName = groupName;
            return this;
        }

        public Builder groupName(String groupName) {
            return groupName(Output.of(groupName));
        }

        public Builder groupType(Output<Integer> groupType) {
            $.groupType = groupType;
            return this;
        }

        public Builder groupType(Integer groupType) {
            return groupType(Output.of(groupType));
        }

        public Builder ldapGroupDn(@Nullable Output<String> ldapGroupDn) {
            $.ldapGroupDn = ldapGroupDn;
            return this;
        }

        public Builder ldapGroupDn(String ldapGroupDn) {
            return ldapGroupDn(Output.of(ldapGroupDn));
        }

        public GroupArgs build() {
            if ($.groupName == null) {
                throw new MissingRequiredPropertyException("GroupArgs", "groupName");
            }
            if ($.groupType == null) {
                throw new MissingRequiredPropertyException("GroupArgs", "groupType");
            }
            return $;
        }
    }

}
