// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.PreheatInstanceArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.PreheatInstanceState;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * ### Basic Usage
 * 
 * ### Usage with Authentication
 * 
 * ## Import
 * 
 * The &lt;span pulumi-lang-nodejs=&#34;`harbor.PreheatInstance`&#34; pulumi-lang-dotnet=&#34;`harbor.PreheatInstance`&#34; pulumi-lang-go=&#34;`PreheatInstance`&#34; pulumi-lang-python=&#34;`PreheatInstance`&#34; pulumi-lang-yaml=&#34;`harbor.PreheatInstance`&#34; pulumi-lang-java=&#34;`harbor.PreheatInstance`&#34; pulumi-lang-hcl=&#34;`harbor_preheat_instance`&#34;&gt;`harbor.PreheatInstance`&lt;/span&gt; resource can be imported using the preheat instance ID.
 * 
 * ```sh
 * $ pulumi import harbor:index/preheatInstance:PreheatInstance example /p2p/preheat/instances/example-preheat-instance
 * ```
 * 
 */
@ResourceType(type="harbor:index/preheatInstance:PreheatInstance")
public class PreheatInstance extends com.pulumi.resources.CustomResource {
    /**
     * The authentication mode for the preheat instance. Must be either &#34;NONE&#34;, &#34;BASIC&#34;, or &#34;OAUTH&#34;. Defaults to &#34;NONE&#34;.
     * 
     */
    @Export(name="authMode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> authMode;

    /**
     * @return The authentication mode for the preheat instance. Must be either &#34;NONE&#34;, &#34;BASIC&#34;, or &#34;OAUTH&#34;. Defaults to &#34;NONE&#34;.
     * 
     */
    public Output<Optional<String>> authMode() {
        return Codegen.optional(this.authMode);
    }
    /**
     * Whether the preheat instance is the default instance. Defaults to false.
     * 
     */
    @Export(name="default", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> default_;

    /**
     * @return Whether the preheat instance is the default instance. Defaults to false.
     * 
     */
    public Output<Optional<Boolean>> default_() {
        return Codegen.optional(this.default_);
    }
    /**
     * The description of the preheat instance. Defaults to an empty string.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description of the preheat instance. Defaults to an empty string.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Whether the preheat instance is enabled. Defaults to true.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enabled;

    /**
     * @return Whether the preheat instance is enabled. Defaults to true.
     * 
     */
    public Output<Optional<Boolean>> enabled() {
        return Codegen.optional(this.enabled);
    }
    /**
     * The endpoint of the preheat instance.
     * 
     */
    @Export(name="endpoint", refs={String.class}, tree="[0]")
    private Output<String> endpoint;

    /**
     * @return The endpoint of the preheat instance.
     * 
     */
    public Output<String> endpoint() {
        return this.endpoint;
    }
    /**
     * Whether to allow insecure connections to the preheat instance. Defaults to false.
     * 
     */
    @Export(name="insecure", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> insecure;

    /**
     * @return Whether to allow insecure connections to the preheat instance. Defaults to false.
     * 
     */
    public Output<Optional<Boolean>> insecure() {
        return Codegen.optional(this.insecure);
    }
    /**
     * The name of the preheat instance.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the preheat instance.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The password for the preheat instance. Required if &lt;span pulumi-lang-nodejs=&#34;`authMode`&#34; pulumi-lang-dotnet=&#34;`AuthMode`&#34; pulumi-lang-go=&#34;`authMode`&#34; pulumi-lang-python=&#34;`auth_mode`&#34; pulumi-lang-yaml=&#34;`authMode`&#34; pulumi-lang-java=&#34;`authMode`&#34; pulumi-lang-hcl=&#34;`auth_mode`&#34;&gt;`authMode`&lt;/span&gt; is &#34;BASIC&#34;. Defaults to an empty string.
     * 
     */
    @Export(name="password", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> password;

    /**
     * @return The password for the preheat instance. Required if &lt;span pulumi-lang-nodejs=&#34;`authMode`&#34; pulumi-lang-dotnet=&#34;`AuthMode`&#34; pulumi-lang-go=&#34;`authMode`&#34; pulumi-lang-python=&#34;`auth_mode`&#34; pulumi-lang-yaml=&#34;`authMode`&#34; pulumi-lang-java=&#34;`authMode`&#34; pulumi-lang-hcl=&#34;`auth_mode`&#34;&gt;`authMode`&lt;/span&gt; is &#34;BASIC&#34;. Defaults to an empty string.
     * 
     */
    public Output<Optional<String>> password() {
        return Codegen.optional(this.password);
    }
    /**
     * The token for the preheat instance. Required if &lt;span pulumi-lang-nodejs=&#34;`authMode`&#34; pulumi-lang-dotnet=&#34;`AuthMode`&#34; pulumi-lang-go=&#34;`authMode`&#34; pulumi-lang-python=&#34;`auth_mode`&#34; pulumi-lang-yaml=&#34;`authMode`&#34; pulumi-lang-java=&#34;`authMode`&#34; pulumi-lang-hcl=&#34;`auth_mode`&#34;&gt;`authMode`&lt;/span&gt; is &#34;OAUTH&#34;. Defaults to an empty string.
     * 
     */
    @Export(name="token", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> token;

    /**
     * @return The token for the preheat instance. Required if &lt;span pulumi-lang-nodejs=&#34;`authMode`&#34; pulumi-lang-dotnet=&#34;`AuthMode`&#34; pulumi-lang-go=&#34;`authMode`&#34; pulumi-lang-python=&#34;`auth_mode`&#34; pulumi-lang-yaml=&#34;`authMode`&#34; pulumi-lang-java=&#34;`authMode`&#34; pulumi-lang-hcl=&#34;`auth_mode`&#34;&gt;`authMode`&lt;/span&gt; is &#34;OAUTH&#34;. Defaults to an empty string.
     * 
     */
    public Output<Optional<String>> token() {
        return Codegen.optional(this.token);
    }
    /**
     * The username for the preheat instance. Required if &lt;span pulumi-lang-nodejs=&#34;`authMode`&#34; pulumi-lang-dotnet=&#34;`AuthMode`&#34; pulumi-lang-go=&#34;`authMode`&#34; pulumi-lang-python=&#34;`auth_mode`&#34; pulumi-lang-yaml=&#34;`authMode`&#34; pulumi-lang-java=&#34;`authMode`&#34; pulumi-lang-hcl=&#34;`auth_mode`&#34;&gt;`authMode`&lt;/span&gt; is &#34;BASIC&#34;. Defaults to an empty string.
     * 
     */
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> username;

    /**
     * @return The username for the preheat instance. Required if &lt;span pulumi-lang-nodejs=&#34;`authMode`&#34; pulumi-lang-dotnet=&#34;`AuthMode`&#34; pulumi-lang-go=&#34;`authMode`&#34; pulumi-lang-python=&#34;`auth_mode`&#34; pulumi-lang-yaml=&#34;`authMode`&#34; pulumi-lang-java=&#34;`authMode`&#34; pulumi-lang-hcl=&#34;`auth_mode`&#34;&gt;`authMode`&lt;/span&gt; is &#34;BASIC&#34;. Defaults to an empty string.
     * 
     */
    public Output<Optional<String>> username() {
        return Codegen.optional(this.username);
    }
    /**
     * The vendor of the preheat instance. Must be either &#34;dragonfly&#34; or &#34;kraken&#34;.
     * 
     */
    @Export(name="vendor", refs={String.class}, tree="[0]")
    private Output<String> vendor;

    /**
     * @return The vendor of the preheat instance. Must be either &#34;dragonfly&#34; or &#34;kraken&#34;.
     * 
     */
    public Output<String> vendor() {
        return this.vendor;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PreheatInstance(java.lang.String name) {
        this(name, PreheatInstanceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PreheatInstance(java.lang.String name, PreheatInstanceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PreheatInstance(java.lang.String name, PreheatInstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/preheatInstance:PreheatInstance", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private PreheatInstance(java.lang.String name, Output<java.lang.String> id, @Nullable PreheatInstanceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/preheatInstance:PreheatInstance", name, state, makeResourceOptions(options, id), false);
    }

    private static PreheatInstanceArgs makeArgs(PreheatInstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PreheatInstanceArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-harbor")
            .additionalSecretOutputs(List.of(
                "password",
                "token"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PreheatInstance get(java.lang.String name, Output<java.lang.String> id, @Nullable PreheatInstanceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PreheatInstance(name, id, state, options);
    }
}
