// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProjectMemberGroupArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectMemberGroupArgs Empty = new ProjectMemberGroupArgs();

    @Import(name="groupId")
    private @Nullable Output<Integer> groupId;

    public Optional<Output<Integer>> groupId() {
        return Optional.ofNullable(this.groupId);
    }

    @Import(name="groupName")
    private @Nullable Output<String> groupName;

    public Optional<Output<String>> groupName() {
        return Optional.ofNullable(this.groupName);
    }

    @Import(name="ldapGroupDn")
    private @Nullable Output<String> ldapGroupDn;

    public Optional<Output<String>> ldapGroupDn() {
        return Optional.ofNullable(this.ldapGroupDn);
    }

    /**
     * The project id of the project that the entity will have access to.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The project id of the project that the entity will have access to.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * The permissions that the entity will be granted.
     * 
     */
    @Import(name="role", required=true)
    private Output<String> role;

    /**
     * @return The permissions that the entity will be granted.
     * 
     */
    public Output<String> role() {
        return this.role;
    }

    /**
     * The group type.  Can be set to `&#34;ldap&#34;`, `&#34;internal&#34;` or `&#34;oidc&#34;`.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The group type.  Can be set to `&#34;ldap&#34;`, `&#34;internal&#34;` or `&#34;oidc&#34;`.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private ProjectMemberGroupArgs() {}

    private ProjectMemberGroupArgs(ProjectMemberGroupArgs $) {
        this.groupId = $.groupId;
        this.groupName = $.groupName;
        this.ldapGroupDn = $.ldapGroupDn;
        this.projectId = $.projectId;
        this.role = $.role;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectMemberGroupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectMemberGroupArgs $;

        public Builder() {
            $ = new ProjectMemberGroupArgs();
        }

        public Builder(ProjectMemberGroupArgs defaults) {
            $ = new ProjectMemberGroupArgs(Objects.requireNonNull(defaults));
        }

        public Builder groupId(@Nullable Output<Integer> groupId) {
            $.groupId = groupId;
            return this;
        }

        public Builder groupId(Integer groupId) {
            return groupId(Output.of(groupId));
        }

        public Builder groupName(@Nullable Output<String> groupName) {
            $.groupName = groupName;
            return this;
        }

        public Builder groupName(String groupName) {
            return groupName(Output.of(groupName));
        }

        public Builder ldapGroupDn(@Nullable Output<String> ldapGroupDn) {
            $.ldapGroupDn = ldapGroupDn;
            return this;
        }

        public Builder ldapGroupDn(String ldapGroupDn) {
            return ldapGroupDn(Output.of(ldapGroupDn));
        }

        /**
         * @param projectId The project id of the project that the entity will have access to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The project id of the project that the entity will have access to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param role The permissions that the entity will be granted.
         * 
         * @return builder
         * 
         */
        public Builder role(Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The permissions that the entity will be granted.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        /**
         * @param type The group type.  Can be set to `&#34;ldap&#34;`, `&#34;internal&#34;` or `&#34;oidc&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The group type.  Can be set to `&#34;ldap&#34;`, `&#34;internal&#34;` or `&#34;oidc&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ProjectMemberGroupArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("ProjectMemberGroupArgs", "projectId");
            }
            if ($.role == null) {
                throw new MissingRequiredPropertyException("ProjectMemberGroupArgs", "role");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ProjectMemberGroupArgs", "type");
            }
            return $;
        }
    }

}
