// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ProjectMemberUserArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProjectMemberUserArgs Empty = new ProjectMemberUserArgs();

    /**
     * The project id of the project that the entity will have access to.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return The project id of the project that the entity will have access to.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * The permissions that the entity will be granted.
     * 
     */
    @Import(name="role", required=true)
    private Output<String> role;

    /**
     * @return The permissions that the entity will be granted.
     * 
     */
    public Output<String> role() {
        return this.role;
    }

    /**
     * The name of the member entity.
     * 
     */
    @Import(name="userName", required=true)
    private Output<String> userName;

    /**
     * @return The name of the member entity.
     * 
     */
    public Output<String> userName() {
        return this.userName;
    }

    private ProjectMemberUserArgs() {}

    private ProjectMemberUserArgs(ProjectMemberUserArgs $) {
        this.projectId = $.projectId;
        this.role = $.role;
        this.userName = $.userName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProjectMemberUserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProjectMemberUserArgs $;

        public Builder() {
            $ = new ProjectMemberUserArgs();
        }

        public Builder(ProjectMemberUserArgs defaults) {
            $ = new ProjectMemberUserArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param projectId The project id of the project that the entity will have access to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The project id of the project that the entity will have access to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param role The permissions that the entity will be granted.
         * 
         * @return builder
         * 
         */
        public Builder role(Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The permissions that the entity will be granted.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        /**
         * @param userName The name of the member entity.
         * 
         * @return builder
         * 
         */
        public Builder userName(Output<String> userName) {
            $.userName = userName;
            return this;
        }

        /**
         * @param userName The name of the member entity.
         * 
         * @return builder
         * 
         */
        public Builder userName(String userName) {
            return userName(Output.of(userName));
        }

        public ProjectMemberUserArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("ProjectMemberUserArgs", "projectId");
            }
            if ($.role == null) {
                throw new MissingRequiredPropertyException("ProjectMemberUserArgs", "role");
            }
            if ($.userName == null) {
                throw new MissingRequiredPropertyException("ProjectMemberUserArgs", "userName");
            }
            return $;
        }
    }

}
