// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.RegistryArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.RegistryState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import harbor:index/registry:Registry main /registries/7
 * ```
 * 
 */
@ResourceType(type="harbor:index/registry:Registry")
public class Registry extends com.pulumi.resources.CustomResource {
    @Export(name="accessId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accessId;

    public Output<Optional<String>> accessId() {
        return Codegen.optional(this.accessId);
    }
    @Export(name="accessSecret", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accessSecret;

    public Output<Optional<String>> accessSecret() {
        return Codegen.optional(this.accessSecret);
    }
    @Export(name="caCertificate", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> caCertificate;

    public Output<Optional<String>> caCertificate() {
        return Codegen.optional(this.caCertificate);
    }
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The URL endpoint for the external container register i.e. `&#34;https://hub.docker.com&#34;`
     * 
     */
    @Export(name="endpointUrl", refs={String.class}, tree="[0]")
    private Output<String> endpointUrl;

    /**
     * @return The URL endpoint for the external container register i.e. `&#34;https://hub.docker.com&#34;`
     * 
     */
    public Output<String> endpointUrl() {
        return this.endpointUrl;
    }
    @Export(name="insecure", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> insecure;

    public Output<Optional<Boolean>> insecure() {
        return Codegen.optional(this.insecure);
    }
    /**
     * The name of the register.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the register.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The name of the provider.
     * 
     */
    @Export(name="providerName", refs={String.class}, tree="[0]")
    private Output<String> providerName;

    /**
     * @return The name of the provider.
     * 
     */
    public Output<String> providerName() {
        return this.providerName;
    }
    @Export(name="registryId", refs={Integer.class}, tree="[0]")
    private Output<Integer> registryId;

    public Output<Integer> registryId() {
        return this.registryId;
    }
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    public Output<String> status() {
        return this.status;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Registry(java.lang.String name) {
        this(name, RegistryArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Registry(java.lang.String name, RegistryArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Registry(java.lang.String name, RegistryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/registry:Registry", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Registry(java.lang.String name, Output<java.lang.String> id, @Nullable RegistryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/registry:Registry", name, state, makeResourceOptions(options, id), false);
    }

    private static RegistryArgs makeArgs(RegistryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RegistryArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-harbor")
            .additionalSecretOutputs(List.of(
                "accessSecret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Registry get(java.lang.String name, Output<java.lang.String> id, @Nullable RegistryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Registry(name, id, state, options);
    }
}
