// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RegistryArgs extends com.pulumi.resources.ResourceArgs {

    public static final RegistryArgs Empty = new RegistryArgs();

    @Import(name="accessId")
    private @Nullable Output<String> accessId;

    public Optional<Output<String>> accessId() {
        return Optional.ofNullable(this.accessId);
    }

    @Import(name="accessSecret")
    private @Nullable Output<String> accessSecret;

    public Optional<Output<String>> accessSecret() {
        return Optional.ofNullable(this.accessSecret);
    }

    @Import(name="caCertificate")
    private @Nullable Output<String> caCertificate;

    public Optional<Output<String>> caCertificate() {
        return Optional.ofNullable(this.caCertificate);
    }

    @Import(name="description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The URL endpoint for the external container register i.e. `&#34;https://hub.docker.com&#34;`
     * 
     */
    @Import(name="endpointUrl", required=true)
    private Output<String> endpointUrl;

    /**
     * @return The URL endpoint for the external container register i.e. `&#34;https://hub.docker.com&#34;`
     * 
     */
    public Output<String> endpointUrl() {
        return this.endpointUrl;
    }

    @Import(name="insecure")
    private @Nullable Output<Boolean> insecure;

    public Optional<Output<Boolean>> insecure() {
        return Optional.ofNullable(this.insecure);
    }

    /**
     * The name of the register.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the register.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The name of the provider.
     * 
     */
    @Import(name="providerName", required=true)
    private Output<String> providerName;

    /**
     * @return The name of the provider.
     * 
     */
    public Output<String> providerName() {
        return this.providerName;
    }

    private RegistryArgs() {}

    private RegistryArgs(RegistryArgs $) {
        this.accessId = $.accessId;
        this.accessSecret = $.accessSecret;
        this.caCertificate = $.caCertificate;
        this.description = $.description;
        this.endpointUrl = $.endpointUrl;
        this.insecure = $.insecure;
        this.name = $.name;
        this.providerName = $.providerName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RegistryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RegistryArgs $;

        public Builder() {
            $ = new RegistryArgs();
        }

        public Builder(RegistryArgs defaults) {
            $ = new RegistryArgs(Objects.requireNonNull(defaults));
        }

        public Builder accessId(@Nullable Output<String> accessId) {
            $.accessId = accessId;
            return this;
        }

        public Builder accessId(String accessId) {
            return accessId(Output.of(accessId));
        }

        public Builder accessSecret(@Nullable Output<String> accessSecret) {
            $.accessSecret = accessSecret;
            return this;
        }

        public Builder accessSecret(String accessSecret) {
            return accessSecret(Output.of(accessSecret));
        }

        public Builder caCertificate(@Nullable Output<String> caCertificate) {
            $.caCertificate = caCertificate;
            return this;
        }

        public Builder caCertificate(String caCertificate) {
            return caCertificate(Output.of(caCertificate));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param endpointUrl The URL endpoint for the external container register i.e. `&#34;https://hub.docker.com&#34;`
         * 
         * @return builder
         * 
         */
        public Builder endpointUrl(Output<String> endpointUrl) {
            $.endpointUrl = endpointUrl;
            return this;
        }

        /**
         * @param endpointUrl The URL endpoint for the external container register i.e. `&#34;https://hub.docker.com&#34;`
         * 
         * @return builder
         * 
         */
        public Builder endpointUrl(String endpointUrl) {
            return endpointUrl(Output.of(endpointUrl));
        }

        public Builder insecure(@Nullable Output<Boolean> insecure) {
            $.insecure = insecure;
            return this;
        }

        public Builder insecure(Boolean insecure) {
            return insecure(Output.of(insecure));
        }

        /**
         * @param name The name of the register.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the register.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param providerName The name of the provider.
         * 
         * @return builder
         * 
         */
        public Builder providerName(Output<String> providerName) {
            $.providerName = providerName;
            return this;
        }

        /**
         * @param providerName The name of the provider.
         * 
         * @return builder
         * 
         */
        public Builder providerName(String providerName) {
            return providerName(Output.of(providerName));
        }

        public RegistryArgs build() {
            if ($.endpointUrl == null) {
                throw new MissingRequiredPropertyException("RegistryArgs", "endpointUrl");
            }
            if ($.providerName == null) {
                throw new MissingRequiredPropertyException("RegistryArgs", "providerName");
            }
            return $;
        }
    }

}
