// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.RobotAccountArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.RobotAccountState;
import com.pulumiverse.harbor.outputs.RobotAccountPermission;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * ### System Level
 * Introduced in harbor 2.2.0, system level robot accounts can have basically [all available permissions](https://github.com/goharbor/harbor/blob/-/src/common/rbac/const.go) in harbor and are not dependent on a single project.
 * 
 * ### Global
 * 
 * The above example, creates a system level robot account with permissions to
 * - permission to create labels on system level
 * - pull repository across all projects
 * - push repository to project &#34;my-project-name&#34;
 * 
 * ### Project
 * 
 * Other than system level robot accounts, project level robot accounts can interact on project level only.
 * The [available permissions](https://github.com/goharbor/harbor/blob/-/src/common/rbac/const.go) are mostly the same as for system level robots.
 * 
 * ### Project with Write-only Secret
 * 
 * ### Project with Write-only Secret from Ephemeral Random Secret
 * 
 * The above example creates a project level robot account with permissions to
 * - pull repository on project &#34;main&#34;
 * - push repository on project &#34;main&#34;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import harbor:index/robotAccount:RobotAccount system /robots/123
 * ```
 * 
 */
@ResourceType(type="harbor:index/robotAccount:RobotAccount")
public class RobotAccount extends com.pulumi.resources.CustomResource {
    /**
     * The description of the robot account will be displayed in harbor.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return The description of the robot account will be displayed in harbor.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Disables the robot account when set to &lt;span pulumi-lang-nodejs=&#34;`true`&#34; pulumi-lang-dotnet=&#34;`True`&#34; pulumi-lang-go=&#34;`true`&#34; pulumi-lang-python=&#34;`true`&#34; pulumi-lang-yaml=&#34;`true`&#34; pulumi-lang-java=&#34;`true`&#34; pulumi-lang-hcl=&#34;`true`&#34;&gt;`true`&lt;/span&gt;.
     * 
     */
    @Export(name="disable", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> disable;

    /**
     * @return Disables the robot account when set to &lt;span pulumi-lang-nodejs=&#34;`true`&#34; pulumi-lang-dotnet=&#34;`True`&#34; pulumi-lang-go=&#34;`true`&#34; pulumi-lang-python=&#34;`true`&#34; pulumi-lang-yaml=&#34;`true`&#34; pulumi-lang-java=&#34;`true`&#34; pulumi-lang-hcl=&#34;`true`&#34;&gt;`true`&lt;/span&gt;.
     * 
     */
    public Output<Optional<Boolean>> disable() {
        return Codegen.optional(this.disable);
    }
    /**
     * By default, the robot account will not expire. Set it to the amount of days until the account should expire.
     * 
     */
    @Export(name="duration", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> duration;

    /**
     * @return By default, the robot account will not expire. Set it to the amount of days until the account should expire.
     * 
     */
    public Output<Optional<Integer>> duration() {
        return Codegen.optional(this.duration);
    }
    @Export(name="fullName", refs={String.class}, tree="[0]")
    private Output<String> fullName;

    public Output<String> fullName() {
        return this.fullName;
    }
    /**
     * Level of the robot account, currently either &lt;span pulumi-lang-nodejs=&#34;`system`&#34; pulumi-lang-dotnet=&#34;`System`&#34; pulumi-lang-go=&#34;`system`&#34; pulumi-lang-python=&#34;`system`&#34; pulumi-lang-yaml=&#34;`system`&#34; pulumi-lang-java=&#34;`system`&#34; pulumi-lang-hcl=&#34;`system`&#34;&gt;`system`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`project`&#34; pulumi-lang-dotnet=&#34;`Project`&#34; pulumi-lang-go=&#34;`project`&#34; pulumi-lang-python=&#34;`project`&#34; pulumi-lang-yaml=&#34;`project`&#34; pulumi-lang-java=&#34;`project`&#34; pulumi-lang-hcl=&#34;`project`&#34;&gt;`project`&lt;/span&gt;.
     * 
     */
    @Export(name="level", refs={String.class}, tree="[0]")
    private Output<String> level;

    /**
     * @return Level of the robot account, currently either &lt;span pulumi-lang-nodejs=&#34;`system`&#34; pulumi-lang-dotnet=&#34;`System`&#34; pulumi-lang-go=&#34;`system`&#34; pulumi-lang-python=&#34;`system`&#34; pulumi-lang-yaml=&#34;`system`&#34; pulumi-lang-java=&#34;`system`&#34; pulumi-lang-hcl=&#34;`system`&#34;&gt;`system`&lt;/span&gt; or &lt;span pulumi-lang-nodejs=&#34;`project`&#34; pulumi-lang-dotnet=&#34;`Project`&#34; pulumi-lang-go=&#34;`project`&#34; pulumi-lang-python=&#34;`project`&#34; pulumi-lang-yaml=&#34;`project`&#34; pulumi-lang-java=&#34;`project`&#34; pulumi-lang-hcl=&#34;`project`&#34;&gt;`project`&lt;/span&gt;.
     * 
     */
    public Output<String> level() {
        return this.level;
    }
    /**
     * The name of the project that will be created in harbor.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the project that will be created in harbor.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    @Export(name="permissions", refs={List.class,RobotAccountPermission.class}, tree="[0,1]")
    private Output<List<RobotAccountPermission>> permissions;

    public Output<List<RobotAccountPermission>> permissions() {
        return this.permissions;
    }
    @Export(name="robotId", refs={String.class}, tree="[0]")
    private Output<String> robotId;

    public Output<String> robotId() {
        return this.robotId;
    }
    /**
     * The secret of the robot account used for authentication. Defaults to random generated string from Harbor.
     * 
     */
    @Export(name="secret", refs={String.class}, tree="[0]")
    private Output<String> secret;

    /**
     * @return The secret of the robot account used for authentication. Defaults to random generated string from Harbor.
     * 
     */
    public Output<String> secret() {
        return this.secret;
    }
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative for &lt;span pulumi-lang-nodejs=&#34;`secret`&#34; pulumi-lang-dotnet=&#34;`Secret`&#34; pulumi-lang-go=&#34;`secret`&#34; pulumi-lang-python=&#34;`secret`&#34; pulumi-lang-yaml=&#34;`secret`&#34; pulumi-lang-java=&#34;`secret`&#34; pulumi-lang-hcl=&#34;`secret`&#34;&gt;`secret`&lt;/span&gt;. Must be used together with &lt;span pulumi-lang-nodejs=&#34;`secretWoVersion`&#34; pulumi-lang-dotnet=&#34;`SecretWoVersion`&#34; pulumi-lang-go=&#34;`secretWoVersion`&#34; pulumi-lang-python=&#34;`secret_wo_version`&#34; pulumi-lang-yaml=&#34;`secretWoVersion`&#34; pulumi-lang-java=&#34;`secretWoVersion`&#34; pulumi-lang-hcl=&#34;`secret_wo_version`&#34;&gt;`secretWoVersion`&lt;/span&gt;.
     * 
     */
    @Export(name="secretWo", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> secretWo;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative for &lt;span pulumi-lang-nodejs=&#34;`secret`&#34; pulumi-lang-dotnet=&#34;`Secret`&#34; pulumi-lang-go=&#34;`secret`&#34; pulumi-lang-python=&#34;`secret`&#34; pulumi-lang-yaml=&#34;`secret`&#34; pulumi-lang-java=&#34;`secret`&#34; pulumi-lang-hcl=&#34;`secret`&#34;&gt;`secret`&lt;/span&gt;. Must be used together with &lt;span pulumi-lang-nodejs=&#34;`secretWoVersion`&#34; pulumi-lang-dotnet=&#34;`SecretWoVersion`&#34; pulumi-lang-go=&#34;`secretWoVersion`&#34; pulumi-lang-python=&#34;`secret_wo_version`&#34; pulumi-lang-yaml=&#34;`secretWoVersion`&#34; pulumi-lang-java=&#34;`secretWoVersion`&#34; pulumi-lang-hcl=&#34;`secret_wo_version`&#34;&gt;`secretWoVersion`&lt;/span&gt;.
     * 
     */
    public Output<Optional<String>> secretWo() {
        return Codegen.optional(this.secretWo);
    }
    /**
     * Rotation trigger for write-only secret updates. Must be used together with &lt;span pulumi-lang-nodejs=&#34;`secretWo`&#34; pulumi-lang-dotnet=&#34;`SecretWo`&#34; pulumi-lang-go=&#34;`secretWo`&#34; pulumi-lang-python=&#34;`secret_wo`&#34; pulumi-lang-yaml=&#34;`secretWo`&#34; pulumi-lang-java=&#34;`secretWo`&#34; pulumi-lang-hcl=&#34;`secret_wo`&#34;&gt;`secretWo`&lt;/span&gt;.
     * 
     */
    @Export(name="secretWoVersion", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> secretWoVersion;

    /**
     * @return Rotation trigger for write-only secret updates. Must be used together with &lt;span pulumi-lang-nodejs=&#34;`secretWo`&#34; pulumi-lang-dotnet=&#34;`SecretWo`&#34; pulumi-lang-go=&#34;`secretWo`&#34; pulumi-lang-python=&#34;`secret_wo`&#34; pulumi-lang-yaml=&#34;`secretWo`&#34; pulumi-lang-java=&#34;`secretWo`&#34; pulumi-lang-hcl=&#34;`secret_wo`&#34;&gt;`secretWo`&lt;/span&gt;.
     * 
     */
    public Output<Optional<Integer>> secretWoVersion() {
        return Codegen.optional(this.secretWoVersion);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RobotAccount(java.lang.String name) {
        this(name, RobotAccountArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RobotAccount(java.lang.String name, RobotAccountArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RobotAccount(java.lang.String name, RobotAccountArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/robotAccount:RobotAccount", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private RobotAccount(java.lang.String name, Output<java.lang.String> id, @Nullable RobotAccountState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/robotAccount:RobotAccount", name, state, makeResourceOptions(options, id), false);
    }

    private static RobotAccountArgs makeArgs(RobotAccountArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RobotAccountArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-harbor")
            .additionalSecretOutputs(List.of(
                "secret",
                "secretWo"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RobotAccount get(java.lang.String name, Output<java.lang.String> id, @Nullable RobotAccountState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RobotAccount(name, id, state, options);
    }
}
