// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumiverse.harbor.TasksArgs;
import com.pulumiverse.harbor.Utilities;
import com.pulumiverse.harbor.inputs.TasksState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 */
@ResourceType(type="harbor:index/tasks:Tasks")
public class Tasks extends com.pulumi.resources.CustomResource {
    /**
     * The frequency of the vulnerability scanning is done. Can be to **&#34;hourly&#34;**, **&#34;daily&#34;** or **&#34;weekly&#34;**
     * 
     */
    @Export(name="vulnerabilityScanPolicy", refs={String.class}, tree="[0]")
    private Output<String> vulnerabilityScanPolicy;

    /**
     * @return The frequency of the vulnerability scanning is done. Can be to **&#34;hourly&#34;**, **&#34;daily&#34;** or **&#34;weekly&#34;**
     * 
     */
    public Output<String> vulnerabilityScanPolicy() {
        return this.vulnerabilityScanPolicy;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Tasks(java.lang.String name) {
        this(name, TasksArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Tasks(java.lang.String name, TasksArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Tasks(java.lang.String name, TasksArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/tasks:Tasks", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Tasks(java.lang.String name, Output<java.lang.String> id, @Nullable TasksState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("harbor:index/tasks:Tasks", name, state, makeResourceOptions(options, id), false);
    }

    private static TasksArgs makeArgs(TasksArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TasksArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse/pulumi-harbor")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Tasks get(java.lang.String name, Output<java.lang.String> id, @Nullable TasksState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Tasks(name, id, state, options);
    }
}
