# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ConfigSystemArgs', 'ConfigSystem']

@pulumi.input_type
class ConfigSystemArgs:
    def __init__(__self__, *,
                 audit_log_forward_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 banner_message: pulumi.Input[Optional['ConfigSystemBannerMessageArgs']] = None,
                 notification_enable: pulumi.Input[Optional[_builtins.bool]] = None,
                 project_creation_restriction: pulumi.Input[Optional[_builtins.str]] = None,
                 read_only: pulumi.Input[Optional[_builtins.bool]] = None,
                 robot_name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 robot_token_expiration: pulumi.Input[Optional[_builtins.int]] = None,
                 scanner_skip_update_pulltime: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_audit_log_database: pulumi.Input[Optional[_builtins.bool]] = None,
                 storage_per_project: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a ConfigSystem resource.

        :param pulumi.Input[_builtins.str] audit_log_forward_endpoint: The endpoint to forward audit logs to.
        :param pulumi.Input[_builtins.bool] notification_enable: Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        :param pulumi.Input[_builtins.str] project_creation_restriction: Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        :param pulumi.Input[_builtins.bool] read_only: Whether or not the system is in read only mode.
        :param pulumi.Input[_builtins.str] robot_name_prefix: Robot account prefix.
        :param pulumi.Input[_builtins.int] robot_token_expiration: The amount of time in days a robot account will expire.
        :param pulumi.Input[_builtins.bool] scanner_skip_update_pulltime: Whether or not to skip update pull time for scanner.
        :param pulumi.Input[_builtins.bool] skip_audit_log_database: Whether or not to skip audit log database.
        :param pulumi.Input[_builtins.int] storage_per_project: Default quota space per project in GIB. Default is -1 (unlimited).
        """
        if audit_log_forward_endpoint is not None:
            pulumi.set(__self__, "audit_log_forward_endpoint", audit_log_forward_endpoint)
        if banner_message is not None:
            pulumi.set(__self__, "banner_message", banner_message)
        if notification_enable is not None:
            pulumi.set(__self__, "notification_enable", notification_enable)
        if project_creation_restriction is not None:
            pulumi.set(__self__, "project_creation_restriction", project_creation_restriction)
        if read_only is not None:
            pulumi.set(__self__, "read_only", read_only)
        if robot_name_prefix is not None:
            pulumi.set(__self__, "robot_name_prefix", robot_name_prefix)
        if robot_token_expiration is not None:
            pulumi.set(__self__, "robot_token_expiration", robot_token_expiration)
        if scanner_skip_update_pulltime is not None:
            pulumi.set(__self__, "scanner_skip_update_pulltime", scanner_skip_update_pulltime)
        if skip_audit_log_database is not None:
            pulumi.set(__self__, "skip_audit_log_database", skip_audit_log_database)
        if storage_per_project is not None:
            pulumi.set(__self__, "storage_per_project", storage_per_project)

    @_builtins.property
    @pulumi.getter(name="auditLogForwardEndpoint")
    def audit_log_forward_endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The endpoint to forward audit logs to.
        """
        return pulumi.get(self, "audit_log_forward_endpoint")

    @audit_log_forward_endpoint.setter
    def audit_log_forward_endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "audit_log_forward_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="bannerMessage")
    def banner_message(self) -> pulumi.Input[Optional['ConfigSystemBannerMessageArgs']]:
        return pulumi.get(self, "banner_message")

    @banner_message.setter
    def banner_message(self, value: pulumi.Input[Optional['ConfigSystemBannerMessageArgs']]):
        pulumi.set(self, "banner_message", value)

    @_builtins.property
    @pulumi.getter(name="notificationEnable")
    def notification_enable(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        """
        return pulumi.get(self, "notification_enable")

    @notification_enable.setter
    def notification_enable(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "notification_enable", value)

    @_builtins.property
    @pulumi.getter(name="projectCreationRestriction")
    def project_creation_restriction(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        """
        return pulumi.get(self, "project_creation_restriction")

    @project_creation_restriction.setter
    def project_creation_restriction(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_creation_restriction", value)

    @_builtins.property
    @pulumi.getter(name="readOnly")
    def read_only(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not the system is in read only mode.
        """
        return pulumi.get(self, "read_only")

    @read_only.setter
    def read_only(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "read_only", value)

    @_builtins.property
    @pulumi.getter(name="robotNamePrefix")
    def robot_name_prefix(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Robot account prefix.
        """
        return pulumi.get(self, "robot_name_prefix")

    @robot_name_prefix.setter
    def robot_name_prefix(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "robot_name_prefix", value)

    @_builtins.property
    @pulumi.getter(name="robotTokenExpiration")
    def robot_token_expiration(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The amount of time in days a robot account will expire.
        """
        return pulumi.get(self, "robot_token_expiration")

    @robot_token_expiration.setter
    def robot_token_expiration(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "robot_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="scannerSkipUpdatePulltime")
    def scanner_skip_update_pulltime(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not to skip update pull time for scanner.
        """
        return pulumi.get(self, "scanner_skip_update_pulltime")

    @scanner_skip_update_pulltime.setter
    def scanner_skip_update_pulltime(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "scanner_skip_update_pulltime", value)

    @_builtins.property
    @pulumi.getter(name="skipAuditLogDatabase")
    def skip_audit_log_database(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not to skip audit log database.
        """
        return pulumi.get(self, "skip_audit_log_database")

    @skip_audit_log_database.setter
    def skip_audit_log_database(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_audit_log_database", value)

    @_builtins.property
    @pulumi.getter(name="storagePerProject")
    def storage_per_project(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Default quota space per project in GIB. Default is -1 (unlimited).
        """
        return pulumi.get(self, "storage_per_project")

    @storage_per_project.setter
    def storage_per_project(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "storage_per_project", value)


@pulumi.input_type
class _ConfigSystemState:
    def __init__(__self__, *,
                 audit_log_forward_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 banner_message: pulumi.Input[Optional['ConfigSystemBannerMessageArgs']] = None,
                 notification_enable: pulumi.Input[Optional[_builtins.bool]] = None,
                 project_creation_restriction: pulumi.Input[Optional[_builtins.str]] = None,
                 read_only: pulumi.Input[Optional[_builtins.bool]] = None,
                 robot_name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 robot_token_expiration: pulumi.Input[Optional[_builtins.int]] = None,
                 scanner_skip_update_pulltime: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_audit_log_database: pulumi.Input[Optional[_builtins.bool]] = None,
                 storage_per_project: pulumi.Input[Optional[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering ConfigSystem resources.

        :param pulumi.Input[_builtins.str] audit_log_forward_endpoint: The endpoint to forward audit logs to.
        :param pulumi.Input[_builtins.bool] notification_enable: Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        :param pulumi.Input[_builtins.str] project_creation_restriction: Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        :param pulumi.Input[_builtins.bool] read_only: Whether or not the system is in read only mode.
        :param pulumi.Input[_builtins.str] robot_name_prefix: Robot account prefix.
        :param pulumi.Input[_builtins.int] robot_token_expiration: The amount of time in days a robot account will expire.
        :param pulumi.Input[_builtins.bool] scanner_skip_update_pulltime: Whether or not to skip update pull time for scanner.
        :param pulumi.Input[_builtins.bool] skip_audit_log_database: Whether or not to skip audit log database.
        :param pulumi.Input[_builtins.int] storage_per_project: Default quota space per project in GIB. Default is -1 (unlimited).
        """
        if audit_log_forward_endpoint is not None:
            pulumi.set(__self__, "audit_log_forward_endpoint", audit_log_forward_endpoint)
        if banner_message is not None:
            pulumi.set(__self__, "banner_message", banner_message)
        if notification_enable is not None:
            pulumi.set(__self__, "notification_enable", notification_enable)
        if project_creation_restriction is not None:
            pulumi.set(__self__, "project_creation_restriction", project_creation_restriction)
        if read_only is not None:
            pulumi.set(__self__, "read_only", read_only)
        if robot_name_prefix is not None:
            pulumi.set(__self__, "robot_name_prefix", robot_name_prefix)
        if robot_token_expiration is not None:
            pulumi.set(__self__, "robot_token_expiration", robot_token_expiration)
        if scanner_skip_update_pulltime is not None:
            pulumi.set(__self__, "scanner_skip_update_pulltime", scanner_skip_update_pulltime)
        if skip_audit_log_database is not None:
            pulumi.set(__self__, "skip_audit_log_database", skip_audit_log_database)
        if storage_per_project is not None:
            pulumi.set(__self__, "storage_per_project", storage_per_project)

    @_builtins.property
    @pulumi.getter(name="auditLogForwardEndpoint")
    def audit_log_forward_endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The endpoint to forward audit logs to.
        """
        return pulumi.get(self, "audit_log_forward_endpoint")

    @audit_log_forward_endpoint.setter
    def audit_log_forward_endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "audit_log_forward_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="bannerMessage")
    def banner_message(self) -> pulumi.Input[Optional['ConfigSystemBannerMessageArgs']]:
        return pulumi.get(self, "banner_message")

    @banner_message.setter
    def banner_message(self, value: pulumi.Input[Optional['ConfigSystemBannerMessageArgs']]):
        pulumi.set(self, "banner_message", value)

    @_builtins.property
    @pulumi.getter(name="notificationEnable")
    def notification_enable(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        """
        return pulumi.get(self, "notification_enable")

    @notification_enable.setter
    def notification_enable(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "notification_enable", value)

    @_builtins.property
    @pulumi.getter(name="projectCreationRestriction")
    def project_creation_restriction(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        """
        return pulumi.get(self, "project_creation_restriction")

    @project_creation_restriction.setter
    def project_creation_restriction(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project_creation_restriction", value)

    @_builtins.property
    @pulumi.getter(name="readOnly")
    def read_only(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not the system is in read only mode.
        """
        return pulumi.get(self, "read_only")

    @read_only.setter
    def read_only(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "read_only", value)

    @_builtins.property
    @pulumi.getter(name="robotNamePrefix")
    def robot_name_prefix(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Robot account prefix.
        """
        return pulumi.get(self, "robot_name_prefix")

    @robot_name_prefix.setter
    def robot_name_prefix(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "robot_name_prefix", value)

    @_builtins.property
    @pulumi.getter(name="robotTokenExpiration")
    def robot_token_expiration(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The amount of time in days a robot account will expire.
        """
        return pulumi.get(self, "robot_token_expiration")

    @robot_token_expiration.setter
    def robot_token_expiration(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "robot_token_expiration", value)

    @_builtins.property
    @pulumi.getter(name="scannerSkipUpdatePulltime")
    def scanner_skip_update_pulltime(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not to skip update pull time for scanner.
        """
        return pulumi.get(self, "scanner_skip_update_pulltime")

    @scanner_skip_update_pulltime.setter
    def scanner_skip_update_pulltime(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "scanner_skip_update_pulltime", value)

    @_builtins.property
    @pulumi.getter(name="skipAuditLogDatabase")
    def skip_audit_log_database(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether or not to skip audit log database.
        """
        return pulumi.get(self, "skip_audit_log_database")

    @skip_audit_log_database.setter
    def skip_audit_log_database(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_audit_log_database", value)

    @_builtins.property
    @pulumi.getter(name="storagePerProject")
    def storage_per_project(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Default quota space per project in GIB. Default is -1 (unlimited).
        """
        return pulumi.get(self, "storage_per_project")

    @storage_per_project.setter
    def storage_per_project(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "storage_per_project", value)


@pulumi.type_token("harbor:index/configSystem:ConfigSystem")
class ConfigSystem(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 audit_log_forward_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 banner_message: pulumi.Input[Optional[Union['ConfigSystemBannerMessageArgs', 'ConfigSystemBannerMessageArgsDict']]] = None,
                 notification_enable: pulumi.Input[Optional[_builtins.bool]] = None,
                 project_creation_restriction: pulumi.Input[Optional[_builtins.str]] = None,
                 read_only: pulumi.Input[Optional[_builtins.bool]] = None,
                 robot_name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 robot_token_expiration: pulumi.Input[Optional[_builtins.int]] = None,
                 scanner_skip_update_pulltime: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_audit_log_database: pulumi.Input[Optional[_builtins.bool]] = None,
                 storage_per_project: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        ## Example Usage


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] audit_log_forward_endpoint: The endpoint to forward audit logs to.
        :param pulumi.Input[_builtins.bool] notification_enable: Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        :param pulumi.Input[_builtins.str] project_creation_restriction: Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        :param pulumi.Input[_builtins.bool] read_only: Whether or not the system is in read only mode.
        :param pulumi.Input[_builtins.str] robot_name_prefix: Robot account prefix.
        :param pulumi.Input[_builtins.int] robot_token_expiration: The amount of time in days a robot account will expire.
        :param pulumi.Input[_builtins.bool] scanner_skip_update_pulltime: Whether or not to skip update pull time for scanner.
        :param pulumi.Input[_builtins.bool] skip_audit_log_database: Whether or not to skip audit log database.
        :param pulumi.Input[_builtins.int] storage_per_project: Default quota space per project in GIB. Default is -1 (unlimited).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ConfigSystemArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage


        :param str resource_name: The name of the resource.
        :param ConfigSystemArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConfigSystemArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 audit_log_forward_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 banner_message: pulumi.Input[Optional[Union['ConfigSystemBannerMessageArgs', 'ConfigSystemBannerMessageArgsDict']]] = None,
                 notification_enable: pulumi.Input[Optional[_builtins.bool]] = None,
                 project_creation_restriction: pulumi.Input[Optional[_builtins.str]] = None,
                 read_only: pulumi.Input[Optional[_builtins.bool]] = None,
                 robot_name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 robot_token_expiration: pulumi.Input[Optional[_builtins.int]] = None,
                 scanner_skip_update_pulltime: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_audit_log_database: pulumi.Input[Optional[_builtins.bool]] = None,
                 storage_per_project: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConfigSystemArgs.__new__(ConfigSystemArgs)

            __props__.__dict__["audit_log_forward_endpoint"] = audit_log_forward_endpoint
            __props__.__dict__["banner_message"] = banner_message
            __props__.__dict__["notification_enable"] = notification_enable
            __props__.__dict__["project_creation_restriction"] = project_creation_restriction
            __props__.__dict__["read_only"] = read_only
            __props__.__dict__["robot_name_prefix"] = robot_name_prefix
            __props__.__dict__["robot_token_expiration"] = robot_token_expiration
            __props__.__dict__["scanner_skip_update_pulltime"] = scanner_skip_update_pulltime
            __props__.__dict__["skip_audit_log_database"] = skip_audit_log_database
            __props__.__dict__["storage_per_project"] = storage_per_project
        super(ConfigSystem, __self__).__init__(
            'harbor:index/configSystem:ConfigSystem',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            audit_log_forward_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
            banner_message: pulumi.Input[Optional[Union['ConfigSystemBannerMessageArgs', 'ConfigSystemBannerMessageArgsDict']]] = None,
            notification_enable: pulumi.Input[Optional[_builtins.bool]] = None,
            project_creation_restriction: pulumi.Input[Optional[_builtins.str]] = None,
            read_only: pulumi.Input[Optional[_builtins.bool]] = None,
            robot_name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
            robot_token_expiration: pulumi.Input[Optional[_builtins.int]] = None,
            scanner_skip_update_pulltime: pulumi.Input[Optional[_builtins.bool]] = None,
            skip_audit_log_database: pulumi.Input[Optional[_builtins.bool]] = None,
            storage_per_project: pulumi.Input[Optional[_builtins.int]] = None) -> 'ConfigSystem':
        """
        Get an existing ConfigSystem resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] audit_log_forward_endpoint: The endpoint to forward audit logs to.
        :param pulumi.Input[_builtins.bool] notification_enable: Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        :param pulumi.Input[_builtins.str] project_creation_restriction: Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        :param pulumi.Input[_builtins.bool] read_only: Whether or not the system is in read only mode.
        :param pulumi.Input[_builtins.str] robot_name_prefix: Robot account prefix.
        :param pulumi.Input[_builtins.int] robot_token_expiration: The amount of time in days a robot account will expire.
        :param pulumi.Input[_builtins.bool] scanner_skip_update_pulltime: Whether or not to skip update pull time for scanner.
        :param pulumi.Input[_builtins.bool] skip_audit_log_database: Whether or not to skip audit log database.
        :param pulumi.Input[_builtins.int] storage_per_project: Default quota space per project in GIB. Default is -1 (unlimited).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConfigSystemState.__new__(_ConfigSystemState)

        __props__.__dict__["audit_log_forward_endpoint"] = audit_log_forward_endpoint
        __props__.__dict__["banner_message"] = banner_message
        __props__.__dict__["notification_enable"] = notification_enable
        __props__.__dict__["project_creation_restriction"] = project_creation_restriction
        __props__.__dict__["read_only"] = read_only
        __props__.__dict__["robot_name_prefix"] = robot_name_prefix
        __props__.__dict__["robot_token_expiration"] = robot_token_expiration
        __props__.__dict__["scanner_skip_update_pulltime"] = scanner_skip_update_pulltime
        __props__.__dict__["skip_audit_log_database"] = skip_audit_log_database
        __props__.__dict__["storage_per_project"] = storage_per_project
        return ConfigSystem(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="auditLogForwardEndpoint")
    def audit_log_forward_endpoint(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The endpoint to forward audit logs to.
        """
        return pulumi.get(self, "audit_log_forward_endpoint")

    @_builtins.property
    @pulumi.getter(name="bannerMessage")
    def banner_message(self) -> pulumi.Output[Optional['outputs.ConfigSystemBannerMessage']]:
        return pulumi.get(self, "banner_message")

    @_builtins.property
    @pulumi.getter(name="notificationEnable")
    def notification_enable(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether or not webhook/notification functionality is enabled globally. When `false`, all project-level webhook policies are silently ignored. Defaults to `true`.
        """
        return pulumi.get(self, "notification_enable")

    @_builtins.property
    @pulumi.getter(name="projectCreationRestriction")
    def project_creation_restriction(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Who can create projects within Harbor. Can be `"adminonly"` or `"everyone"`
        """
        return pulumi.get(self, "project_creation_restriction")

    @_builtins.property
    @pulumi.getter(name="readOnly")
    def read_only(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether or not the system is in read only mode.
        """
        return pulumi.get(self, "read_only")

    @_builtins.property
    @pulumi.getter(name="robotNamePrefix")
    def robot_name_prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Robot account prefix.
        """
        return pulumi.get(self, "robot_name_prefix")

    @_builtins.property
    @pulumi.getter(name="robotTokenExpiration")
    def robot_token_expiration(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The amount of time in days a robot account will expire.
        """
        return pulumi.get(self, "robot_token_expiration")

    @_builtins.property
    @pulumi.getter(name="scannerSkipUpdatePulltime")
    def scanner_skip_update_pulltime(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether or not to skip update pull time for scanner.
        """
        return pulumi.get(self, "scanner_skip_update_pulltime")

    @_builtins.property
    @pulumi.getter(name="skipAuditLogDatabase")
    def skip_audit_log_database(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether or not to skip audit log database.
        """
        return pulumi.get(self, "skip_audit_log_database")

    @_builtins.property
    @pulumi.getter(name="storagePerProject")
    def storage_per_project(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Default quota space per project in GIB. Default is -1 (unlimited).
        """
        return pulumi.get(self, "storage_per_project")

