# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ConfigAuthArgs', 'ConfigAuth']

@pulumi.input_type
class ConfigAuthArgs:
    def __init__(__self__, *,
                 auth_mode: pulumi.Input[_builtins.str],
                 ldap_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_admin_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_gid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_membership: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_admin_group: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_auto_onboard: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret_wo_version: pulumi.Input[Optional[_builtins.int]] = None,
                 oidc_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_groups_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_logout: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_user_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_auth_mode: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a ConfigAuth resource.

        :param pulumi.Input[_builtins.str] auth_mode: Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        pulumi.set(__self__, "auth_mode", auth_mode)
        if ldap_base_dn is not None:
            pulumi.set(__self__, "ldap_base_dn", ldap_base_dn)
        if ldap_filter is not None:
            pulumi.set(__self__, "ldap_filter", ldap_filter)
        if ldap_group_admin_dn is not None:
            pulumi.set(__self__, "ldap_group_admin_dn", ldap_group_admin_dn)
        if ldap_group_base_dn is not None:
            pulumi.set(__self__, "ldap_group_base_dn", ldap_group_base_dn)
        if ldap_group_filter is not None:
            pulumi.set(__self__, "ldap_group_filter", ldap_group_filter)
        if ldap_group_gid is not None:
            pulumi.set(__self__, "ldap_group_gid", ldap_group_gid)
        if ldap_group_membership is not None:
            pulumi.set(__self__, "ldap_group_membership", ldap_group_membership)
        if ldap_group_scope is not None:
            pulumi.set(__self__, "ldap_group_scope", ldap_group_scope)
        if ldap_group_uid is not None:
            pulumi.set(__self__, "ldap_group_uid", ldap_group_uid)
        if ldap_scope is not None:
            pulumi.set(__self__, "ldap_scope", ldap_scope)
        if ldap_search_dn is not None:
            pulumi.set(__self__, "ldap_search_dn", ldap_search_dn)
        if ldap_search_password is not None:
            pulumi.set(__self__, "ldap_search_password", ldap_search_password)
        if ldap_uid is not None:
            pulumi.set(__self__, "ldap_uid", ldap_uid)
        if ldap_url is not None:
            pulumi.set(__self__, "ldap_url", ldap_url)
        if ldap_verify_cert is not None:
            pulumi.set(__self__, "ldap_verify_cert", ldap_verify_cert)
        if oidc_admin_group is not None:
            pulumi.set(__self__, "oidc_admin_group", oidc_admin_group)
        if oidc_auto_onboard is not None:
            pulumi.set(__self__, "oidc_auto_onboard", oidc_auto_onboard)
        if oidc_client_id is not None:
            pulumi.set(__self__, "oidc_client_id", oidc_client_id)
        if oidc_client_secret is not None:
            pulumi.set(__self__, "oidc_client_secret", oidc_client_secret)
        if oidc_client_secret_wo_version is not None:
            pulumi.set(__self__, "oidc_client_secret_wo_version", oidc_client_secret_wo_version)
        if oidc_endpoint is not None:
            pulumi.set(__self__, "oidc_endpoint", oidc_endpoint)
        if oidc_group_filter is not None:
            pulumi.set(__self__, "oidc_group_filter", oidc_group_filter)
        if oidc_groups_claim is not None:
            pulumi.set(__self__, "oidc_groups_claim", oidc_groups_claim)
        if oidc_logout is not None:
            pulumi.set(__self__, "oidc_logout", oidc_logout)
        if oidc_name is not None:
            pulumi.set(__self__, "oidc_name", oidc_name)
        if oidc_scope is not None:
            pulumi.set(__self__, "oidc_scope", oidc_scope)
        if oidc_user_claim is not None:
            pulumi.set(__self__, "oidc_user_claim", oidc_user_claim)
        if oidc_verify_cert is not None:
            pulumi.set(__self__, "oidc_verify_cert", oidc_verify_cert)
        if primary_auth_mode is not None:
            pulumi.set(__self__, "primary_auth_mode", primary_auth_mode)

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> pulumi.Input[_builtins.str]:
        """
        Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        return pulumi.get(self, "auth_mode")

    @auth_mode.setter
    def auth_mode(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "auth_mode", value)

    @_builtins.property
    @pulumi.getter(name="ldapBaseDn")
    def ldap_base_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_base_dn")

    @ldap_base_dn.setter
    def ldap_base_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_base_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapFilter")
    def ldap_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_filter")

    @ldap_filter.setter
    def ldap_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_filter", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupAdminDn")
    def ldap_group_admin_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_admin_dn")

    @ldap_group_admin_dn.setter
    def ldap_group_admin_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_admin_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupBaseDn")
    def ldap_group_base_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_base_dn")

    @ldap_group_base_dn.setter
    def ldap_group_base_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_base_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupFilter")
    def ldap_group_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_filter")

    @ldap_group_filter.setter
    def ldap_group_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_filter", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupGid")
    def ldap_group_gid(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_gid")

    @ldap_group_gid.setter
    def ldap_group_gid(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_gid", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupMembership")
    def ldap_group_membership(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_membership")

    @ldap_group_membership.setter
    def ldap_group_membership(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_membership", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupScope")
    def ldap_group_scope(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_scope")

    @ldap_group_scope.setter
    def ldap_group_scope(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_scope", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupUid")
    def ldap_group_uid(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_uid")

    @ldap_group_uid.setter
    def ldap_group_uid(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_uid", value)

    @_builtins.property
    @pulumi.getter(name="ldapScope")
    def ldap_scope(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_scope")

    @ldap_scope.setter
    def ldap_scope(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_scope", value)

    @_builtins.property
    @pulumi.getter(name="ldapSearchDn")
    def ldap_search_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_search_dn")

    @ldap_search_dn.setter
    def ldap_search_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_search_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapSearchPassword")
    def ldap_search_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_search_password")

    @ldap_search_password.setter
    def ldap_search_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_search_password", value)

    @_builtins.property
    @pulumi.getter(name="ldapUid")
    def ldap_uid(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_uid")

    @ldap_uid.setter
    def ldap_uid(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_uid", value)

    @_builtins.property
    @pulumi.getter(name="ldapUrl")
    def ldap_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_url")

    @ldap_url.setter
    def ldap_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_url", value)

    @_builtins.property
    @pulumi.getter(name="ldapVerifyCert")
    def ldap_verify_cert(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "ldap_verify_cert")

    @ldap_verify_cert.setter
    def ldap_verify_cert(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ldap_verify_cert", value)

    @_builtins.property
    @pulumi.getter(name="oidcAdminGroup")
    def oidc_admin_group(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_admin_group")

    @oidc_admin_group.setter
    def oidc_admin_group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_admin_group", value)

    @_builtins.property
    @pulumi.getter(name="oidcAutoOnboard")
    def oidc_auto_onboard(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_auto_onboard")

    @oidc_auto_onboard.setter
    def oidc_auto_onboard(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "oidc_auto_onboard", value)

    @_builtins.property
    @pulumi.getter(name="oidcClientId")
    def oidc_client_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_client_id")

    @oidc_client_id.setter
    def oidc_client_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_client_id", value)

    @_builtins.property
    @pulumi.getter(name="oidcClientSecret")
    def oidc_client_secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_client_secret")

    @oidc_client_secret.setter
    def oidc_client_secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_client_secret", value)

    @_builtins.property
    @pulumi.getter(name="oidcClientSecretWoVersion")
    def oidc_client_secret_wo_version(self) -> pulumi.Input[Optional[_builtins.int]]:
        return pulumi.get(self, "oidc_client_secret_wo_version")

    @oidc_client_secret_wo_version.setter
    def oidc_client_secret_wo_version(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "oidc_client_secret_wo_version", value)

    @_builtins.property
    @pulumi.getter(name="oidcEndpoint")
    def oidc_endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_endpoint")

    @oidc_endpoint.setter
    def oidc_endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="oidcGroupFilter")
    def oidc_group_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_group_filter")

    @oidc_group_filter.setter
    def oidc_group_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_group_filter", value)

    @_builtins.property
    @pulumi.getter(name="oidcGroupsClaim")
    def oidc_groups_claim(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_groups_claim")

    @oidc_groups_claim.setter
    def oidc_groups_claim(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_groups_claim", value)

    @_builtins.property
    @pulumi.getter(name="oidcLogout")
    def oidc_logout(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_logout")

    @oidc_logout.setter
    def oidc_logout(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "oidc_logout", value)

    @_builtins.property
    @pulumi.getter(name="oidcName")
    def oidc_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_name")

    @oidc_name.setter
    def oidc_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_name", value)

    @_builtins.property
    @pulumi.getter(name="oidcScope")
    def oidc_scope(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_scope")

    @oidc_scope.setter
    def oidc_scope(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_scope", value)

    @_builtins.property
    @pulumi.getter(name="oidcUserClaim")
    def oidc_user_claim(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_user_claim")

    @oidc_user_claim.setter
    def oidc_user_claim(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_user_claim", value)

    @_builtins.property
    @pulumi.getter(name="oidcVerifyCert")
    def oidc_verify_cert(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_verify_cert")

    @oidc_verify_cert.setter
    def oidc_verify_cert(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "oidc_verify_cert", value)

    @_builtins.property
    @pulumi.getter(name="primaryAuthMode")
    def primary_auth_mode(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "primary_auth_mode")

    @primary_auth_mode.setter
    def primary_auth_mode(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "primary_auth_mode", value)


@pulumi.input_type
class _ConfigAuthState:
    def __init__(__self__, *,
                 auth_mode: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_admin_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_gid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_membership: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_admin_group: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_auto_onboard: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret_wo_version: pulumi.Input[Optional[_builtins.int]] = None,
                 oidc_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_groups_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_logout: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_user_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_auth_mode: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering ConfigAuth resources.

        :param pulumi.Input[_builtins.str] auth_mode: Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        if auth_mode is not None:
            pulumi.set(__self__, "auth_mode", auth_mode)
        if ldap_base_dn is not None:
            pulumi.set(__self__, "ldap_base_dn", ldap_base_dn)
        if ldap_filter is not None:
            pulumi.set(__self__, "ldap_filter", ldap_filter)
        if ldap_group_admin_dn is not None:
            pulumi.set(__self__, "ldap_group_admin_dn", ldap_group_admin_dn)
        if ldap_group_base_dn is not None:
            pulumi.set(__self__, "ldap_group_base_dn", ldap_group_base_dn)
        if ldap_group_filter is not None:
            pulumi.set(__self__, "ldap_group_filter", ldap_group_filter)
        if ldap_group_gid is not None:
            pulumi.set(__self__, "ldap_group_gid", ldap_group_gid)
        if ldap_group_membership is not None:
            pulumi.set(__self__, "ldap_group_membership", ldap_group_membership)
        if ldap_group_scope is not None:
            pulumi.set(__self__, "ldap_group_scope", ldap_group_scope)
        if ldap_group_uid is not None:
            pulumi.set(__self__, "ldap_group_uid", ldap_group_uid)
        if ldap_scope is not None:
            pulumi.set(__self__, "ldap_scope", ldap_scope)
        if ldap_search_dn is not None:
            pulumi.set(__self__, "ldap_search_dn", ldap_search_dn)
        if ldap_search_password is not None:
            pulumi.set(__self__, "ldap_search_password", ldap_search_password)
        if ldap_uid is not None:
            pulumi.set(__self__, "ldap_uid", ldap_uid)
        if ldap_url is not None:
            pulumi.set(__self__, "ldap_url", ldap_url)
        if ldap_verify_cert is not None:
            pulumi.set(__self__, "ldap_verify_cert", ldap_verify_cert)
        if oidc_admin_group is not None:
            pulumi.set(__self__, "oidc_admin_group", oidc_admin_group)
        if oidc_auto_onboard is not None:
            pulumi.set(__self__, "oidc_auto_onboard", oidc_auto_onboard)
        if oidc_client_id is not None:
            pulumi.set(__self__, "oidc_client_id", oidc_client_id)
        if oidc_client_secret is not None:
            pulumi.set(__self__, "oidc_client_secret", oidc_client_secret)
        if oidc_client_secret_wo_version is not None:
            pulumi.set(__self__, "oidc_client_secret_wo_version", oidc_client_secret_wo_version)
        if oidc_endpoint is not None:
            pulumi.set(__self__, "oidc_endpoint", oidc_endpoint)
        if oidc_group_filter is not None:
            pulumi.set(__self__, "oidc_group_filter", oidc_group_filter)
        if oidc_groups_claim is not None:
            pulumi.set(__self__, "oidc_groups_claim", oidc_groups_claim)
        if oidc_logout is not None:
            pulumi.set(__self__, "oidc_logout", oidc_logout)
        if oidc_name is not None:
            pulumi.set(__self__, "oidc_name", oidc_name)
        if oidc_scope is not None:
            pulumi.set(__self__, "oidc_scope", oidc_scope)
        if oidc_user_claim is not None:
            pulumi.set(__self__, "oidc_user_claim", oidc_user_claim)
        if oidc_verify_cert is not None:
            pulumi.set(__self__, "oidc_verify_cert", oidc_verify_cert)
        if primary_auth_mode is not None:
            pulumi.set(__self__, "primary_auth_mode", primary_auth_mode)

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        return pulumi.get(self, "auth_mode")

    @auth_mode.setter
    def auth_mode(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "auth_mode", value)

    @_builtins.property
    @pulumi.getter(name="ldapBaseDn")
    def ldap_base_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_base_dn")

    @ldap_base_dn.setter
    def ldap_base_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_base_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapFilter")
    def ldap_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_filter")

    @ldap_filter.setter
    def ldap_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_filter", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupAdminDn")
    def ldap_group_admin_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_admin_dn")

    @ldap_group_admin_dn.setter
    def ldap_group_admin_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_admin_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupBaseDn")
    def ldap_group_base_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_base_dn")

    @ldap_group_base_dn.setter
    def ldap_group_base_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_base_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupFilter")
    def ldap_group_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_filter")

    @ldap_group_filter.setter
    def ldap_group_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_filter", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupGid")
    def ldap_group_gid(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_gid")

    @ldap_group_gid.setter
    def ldap_group_gid(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_gid", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupMembership")
    def ldap_group_membership(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_membership")

    @ldap_group_membership.setter
    def ldap_group_membership(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_membership", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupScope")
    def ldap_group_scope(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_scope")

    @ldap_group_scope.setter
    def ldap_group_scope(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_scope", value)

    @_builtins.property
    @pulumi.getter(name="ldapGroupUid")
    def ldap_group_uid(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_uid")

    @ldap_group_uid.setter
    def ldap_group_uid(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_group_uid", value)

    @_builtins.property
    @pulumi.getter(name="ldapScope")
    def ldap_scope(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_scope")

    @ldap_scope.setter
    def ldap_scope(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_scope", value)

    @_builtins.property
    @pulumi.getter(name="ldapSearchDn")
    def ldap_search_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_search_dn")

    @ldap_search_dn.setter
    def ldap_search_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_search_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapSearchPassword")
    def ldap_search_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_search_password")

    @ldap_search_password.setter
    def ldap_search_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_search_password", value)

    @_builtins.property
    @pulumi.getter(name="ldapUid")
    def ldap_uid(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_uid")

    @ldap_uid.setter
    def ldap_uid(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_uid", value)

    @_builtins.property
    @pulumi.getter(name="ldapUrl")
    def ldap_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_url")

    @ldap_url.setter
    def ldap_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_url", value)

    @_builtins.property
    @pulumi.getter(name="ldapVerifyCert")
    def ldap_verify_cert(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "ldap_verify_cert")

    @ldap_verify_cert.setter
    def ldap_verify_cert(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ldap_verify_cert", value)

    @_builtins.property
    @pulumi.getter(name="oidcAdminGroup")
    def oidc_admin_group(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_admin_group")

    @oidc_admin_group.setter
    def oidc_admin_group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_admin_group", value)

    @_builtins.property
    @pulumi.getter(name="oidcAutoOnboard")
    def oidc_auto_onboard(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_auto_onboard")

    @oidc_auto_onboard.setter
    def oidc_auto_onboard(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "oidc_auto_onboard", value)

    @_builtins.property
    @pulumi.getter(name="oidcClientId")
    def oidc_client_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_client_id")

    @oidc_client_id.setter
    def oidc_client_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_client_id", value)

    @_builtins.property
    @pulumi.getter(name="oidcClientSecret")
    def oidc_client_secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_client_secret")

    @oidc_client_secret.setter
    def oidc_client_secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_client_secret", value)

    @_builtins.property
    @pulumi.getter(name="oidcClientSecretWoVersion")
    def oidc_client_secret_wo_version(self) -> pulumi.Input[Optional[_builtins.int]]:
        return pulumi.get(self, "oidc_client_secret_wo_version")

    @oidc_client_secret_wo_version.setter
    def oidc_client_secret_wo_version(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "oidc_client_secret_wo_version", value)

    @_builtins.property
    @pulumi.getter(name="oidcEndpoint")
    def oidc_endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_endpoint")

    @oidc_endpoint.setter
    def oidc_endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="oidcGroupFilter")
    def oidc_group_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_group_filter")

    @oidc_group_filter.setter
    def oidc_group_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_group_filter", value)

    @_builtins.property
    @pulumi.getter(name="oidcGroupsClaim")
    def oidc_groups_claim(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_groups_claim")

    @oidc_groups_claim.setter
    def oidc_groups_claim(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_groups_claim", value)

    @_builtins.property
    @pulumi.getter(name="oidcLogout")
    def oidc_logout(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_logout")

    @oidc_logout.setter
    def oidc_logout(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "oidc_logout", value)

    @_builtins.property
    @pulumi.getter(name="oidcName")
    def oidc_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_name")

    @oidc_name.setter
    def oidc_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_name", value)

    @_builtins.property
    @pulumi.getter(name="oidcScope")
    def oidc_scope(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_scope")

    @oidc_scope.setter
    def oidc_scope(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_scope", value)

    @_builtins.property
    @pulumi.getter(name="oidcUserClaim")
    def oidc_user_claim(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_user_claim")

    @oidc_user_claim.setter
    def oidc_user_claim(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "oidc_user_claim", value)

    @_builtins.property
    @pulumi.getter(name="oidcVerifyCert")
    def oidc_verify_cert(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_verify_cert")

    @oidc_verify_cert.setter
    def oidc_verify_cert(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "oidc_verify_cert", value)

    @_builtins.property
    @pulumi.getter(name="primaryAuthMode")
    def primary_auth_mode(self) -> pulumi.Input[Optional[_builtins.bool]]:
        return pulumi.get(self, "primary_auth_mode")

    @primary_auth_mode.setter
    def primary_auth_mode(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "primary_auth_mode", value)


@pulumi.type_token("harbor:index/configAuth:ConfigAuth")
class ConfigAuth(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_mode: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_admin_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_gid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_membership: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_admin_group: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_auto_onboard: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret_wo_version: pulumi.Input[Optional[_builtins.int]] = None,
                 oidc_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_groups_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_logout: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_user_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_auth_mode: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        ## Example Usage

        ### OIDC

        ### OIDC with Write-only Client Secret

        ### LDAP


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] auth_mode: Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConfigAuthArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage

        ### OIDC

        ### OIDC with Write-only Client Secret

        ### LDAP


        :param str resource_name: The name of the resource.
        :param ConfigAuthArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConfigAuthArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth_mode: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_admin_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_gid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_membership: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_group_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_search_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_uid: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_admin_group: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_auto_onboard: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_client_secret_wo_version: pulumi.Input[Optional[_builtins.int]] = None,
                 oidc_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_groups_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_logout: pulumi.Input[Optional[_builtins.bool]] = None,
                 oidc_name: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_scope: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_user_claim: pulumi.Input[Optional[_builtins.str]] = None,
                 oidc_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_auth_mode: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConfigAuthArgs.__new__(ConfigAuthArgs)

            if auth_mode is None and not opts.urn:
                raise TypeError("Missing required property 'auth_mode'")
            __props__.__dict__["auth_mode"] = auth_mode
            __props__.__dict__["ldap_base_dn"] = ldap_base_dn
            __props__.__dict__["ldap_filter"] = ldap_filter
            __props__.__dict__["ldap_group_admin_dn"] = ldap_group_admin_dn
            __props__.__dict__["ldap_group_base_dn"] = ldap_group_base_dn
            __props__.__dict__["ldap_group_filter"] = ldap_group_filter
            __props__.__dict__["ldap_group_gid"] = ldap_group_gid
            __props__.__dict__["ldap_group_membership"] = ldap_group_membership
            __props__.__dict__["ldap_group_scope"] = ldap_group_scope
            __props__.__dict__["ldap_group_uid"] = ldap_group_uid
            __props__.__dict__["ldap_scope"] = ldap_scope
            __props__.__dict__["ldap_search_dn"] = ldap_search_dn
            __props__.__dict__["ldap_search_password"] = None if ldap_search_password is None else pulumi.Output.secret(ldap_search_password)
            __props__.__dict__["ldap_uid"] = ldap_uid
            __props__.__dict__["ldap_url"] = ldap_url
            __props__.__dict__["ldap_verify_cert"] = ldap_verify_cert
            __props__.__dict__["oidc_admin_group"] = oidc_admin_group
            __props__.__dict__["oidc_auto_onboard"] = oidc_auto_onboard
            __props__.__dict__["oidc_client_id"] = oidc_client_id
            __props__.__dict__["oidc_client_secret"] = None if oidc_client_secret is None else pulumi.Output.secret(oidc_client_secret)
            __props__.__dict__["oidc_client_secret_wo_version"] = oidc_client_secret_wo_version
            __props__.__dict__["oidc_endpoint"] = oidc_endpoint
            __props__.__dict__["oidc_group_filter"] = oidc_group_filter
            __props__.__dict__["oidc_groups_claim"] = oidc_groups_claim
            __props__.__dict__["oidc_logout"] = oidc_logout
            __props__.__dict__["oidc_name"] = oidc_name
            __props__.__dict__["oidc_scope"] = oidc_scope
            __props__.__dict__["oidc_user_claim"] = oidc_user_claim
            __props__.__dict__["oidc_verify_cert"] = oidc_verify_cert
            __props__.__dict__["primary_auth_mode"] = primary_auth_mode
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["ldapSearchPassword", "oidcClientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ConfigAuth, __self__).__init__(
            'harbor:index/configAuth:ConfigAuth',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth_mode: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_filter: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_admin_dn: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_base_dn: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_gid: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_membership: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_scope: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_group_uid: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_scope: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_search_dn: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_search_password: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_uid: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
            ldap_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
            oidc_admin_group: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_auto_onboard: pulumi.Input[Optional[_builtins.bool]] = None,
            oidc_client_id: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_client_secret: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_client_secret_wo_version: pulumi.Input[Optional[_builtins.int]] = None,
            oidc_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_group_filter: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_groups_claim: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_logout: pulumi.Input[Optional[_builtins.bool]] = None,
            oidc_name: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_scope: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_user_claim: pulumi.Input[Optional[_builtins.str]] = None,
            oidc_verify_cert: pulumi.Input[Optional[_builtins.bool]] = None,
            primary_auth_mode: pulumi.Input[Optional[_builtins.bool]] = None) -> 'ConfigAuth':
        """
        Get an existing ConfigAuth resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] auth_mode: Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConfigAuthState.__new__(_ConfigAuthState)

        __props__.__dict__["auth_mode"] = auth_mode
        __props__.__dict__["ldap_base_dn"] = ldap_base_dn
        __props__.__dict__["ldap_filter"] = ldap_filter
        __props__.__dict__["ldap_group_admin_dn"] = ldap_group_admin_dn
        __props__.__dict__["ldap_group_base_dn"] = ldap_group_base_dn
        __props__.__dict__["ldap_group_filter"] = ldap_group_filter
        __props__.__dict__["ldap_group_gid"] = ldap_group_gid
        __props__.__dict__["ldap_group_membership"] = ldap_group_membership
        __props__.__dict__["ldap_group_scope"] = ldap_group_scope
        __props__.__dict__["ldap_group_uid"] = ldap_group_uid
        __props__.__dict__["ldap_scope"] = ldap_scope
        __props__.__dict__["ldap_search_dn"] = ldap_search_dn
        __props__.__dict__["ldap_search_password"] = ldap_search_password
        __props__.__dict__["ldap_uid"] = ldap_uid
        __props__.__dict__["ldap_url"] = ldap_url
        __props__.__dict__["ldap_verify_cert"] = ldap_verify_cert
        __props__.__dict__["oidc_admin_group"] = oidc_admin_group
        __props__.__dict__["oidc_auto_onboard"] = oidc_auto_onboard
        __props__.__dict__["oidc_client_id"] = oidc_client_id
        __props__.__dict__["oidc_client_secret"] = oidc_client_secret
        __props__.__dict__["oidc_client_secret_wo_version"] = oidc_client_secret_wo_version
        __props__.__dict__["oidc_endpoint"] = oidc_endpoint
        __props__.__dict__["oidc_group_filter"] = oidc_group_filter
        __props__.__dict__["oidc_groups_claim"] = oidc_groups_claim
        __props__.__dict__["oidc_logout"] = oidc_logout
        __props__.__dict__["oidc_name"] = oidc_name
        __props__.__dict__["oidc_scope"] = oidc_scope
        __props__.__dict__["oidc_user_claim"] = oidc_user_claim
        __props__.__dict__["oidc_verify_cert"] = oidc_verify_cert
        __props__.__dict__["primary_auth_mode"] = primary_auth_mode
        return ConfigAuth(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> pulumi.Output[_builtins.str]:
        """
        Harbor authentication mode. Can be `"oidc_auth"`, `"db_auth"` or `"ldap_auth"`. (Default: `"db_auth"`)
        """
        return pulumi.get(self, "auth_mode")

    @_builtins.property
    @pulumi.getter(name="ldapBaseDn")
    def ldap_base_dn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_base_dn")

    @_builtins.property
    @pulumi.getter(name="ldapFilter")
    def ldap_filter(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_filter")

    @_builtins.property
    @pulumi.getter(name="ldapGroupAdminDn")
    def ldap_group_admin_dn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_admin_dn")

    @_builtins.property
    @pulumi.getter(name="ldapGroupBaseDn")
    def ldap_group_base_dn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_base_dn")

    @_builtins.property
    @pulumi.getter(name="ldapGroupFilter")
    def ldap_group_filter(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_filter")

    @_builtins.property
    @pulumi.getter(name="ldapGroupGid")
    def ldap_group_gid(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_gid")

    @_builtins.property
    @pulumi.getter(name="ldapGroupMembership")
    def ldap_group_membership(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_membership")

    @_builtins.property
    @pulumi.getter(name="ldapGroupScope")
    def ldap_group_scope(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_scope")

    @_builtins.property
    @pulumi.getter(name="ldapGroupUid")
    def ldap_group_uid(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_group_uid")

    @_builtins.property
    @pulumi.getter(name="ldapScope")
    def ldap_scope(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_scope")

    @_builtins.property
    @pulumi.getter(name="ldapSearchDn")
    def ldap_search_dn(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_search_dn")

    @_builtins.property
    @pulumi.getter(name="ldapSearchPassword")
    def ldap_search_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_search_password")

    @_builtins.property
    @pulumi.getter(name="ldapUid")
    def ldap_uid(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_uid")

    @_builtins.property
    @pulumi.getter(name="ldapUrl")
    def ldap_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ldap_url")

    @_builtins.property
    @pulumi.getter(name="ldapVerifyCert")
    def ldap_verify_cert(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "ldap_verify_cert")

    @_builtins.property
    @pulumi.getter(name="oidcAdminGroup")
    def oidc_admin_group(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_admin_group")

    @_builtins.property
    @pulumi.getter(name="oidcAutoOnboard")
    def oidc_auto_onboard(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_auto_onboard")

    @_builtins.property
    @pulumi.getter(name="oidcClientId")
    def oidc_client_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_client_id")

    @_builtins.property
    @pulumi.getter(name="oidcClientSecret")
    def oidc_client_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_client_secret")

    @_builtins.property
    @pulumi.getter(name="oidcClientSecretWoVersion")
    def oidc_client_secret_wo_version(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "oidc_client_secret_wo_version")

    @_builtins.property
    @pulumi.getter(name="oidcEndpoint")
    def oidc_endpoint(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_endpoint")

    @_builtins.property
    @pulumi.getter(name="oidcGroupFilter")
    def oidc_group_filter(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_group_filter")

    @_builtins.property
    @pulumi.getter(name="oidcGroupsClaim")
    def oidc_groups_claim(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_groups_claim")

    @_builtins.property
    @pulumi.getter(name="oidcLogout")
    def oidc_logout(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_logout")

    @_builtins.property
    @pulumi.getter(name="oidcName")
    def oidc_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_name")

    @_builtins.property
    @pulumi.getter(name="oidcScope")
    def oidc_scope(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_scope")

    @_builtins.property
    @pulumi.getter(name="oidcUserClaim")
    def oidc_user_claim(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "oidc_user_claim")

    @_builtins.property
    @pulumi.getter(name="oidcVerifyCert")
    def oidc_verify_cert(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "oidc_verify_cert")

    @_builtins.property
    @pulumi.getter(name="primaryAuthMode")
    def primary_auth_mode(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "primary_auth_mode")

