# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['GarbageCollectionArgs', 'GarbageCollection']

@pulumi.input_type
class GarbageCollectionArgs:
    def __init__(__self__, *,
                 schedule: pulumi.Input[_builtins.str],
                 delete_untagged: pulumi.Input[Optional[_builtins.bool]] = None,
                 workers: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a GarbageCollection resource.

        :param pulumi.Input[_builtins.str] schedule: Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        :param pulumi.Input[_builtins.bool] delete_untagged: Allow garbage collection on untagged artifacts.
        :param pulumi.Input[_builtins.int] workers: Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        pulumi.set(__self__, "schedule", schedule)
        if delete_untagged is not None:
            pulumi.set(__self__, "delete_untagged", delete_untagged)
        if workers is not None:
            pulumi.set(__self__, "workers", workers)

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Input[_builtins.str]:
        """
        Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        """
        return pulumi.get(self, "schedule")

    @schedule.setter
    def schedule(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "schedule", value)

    @_builtins.property
    @pulumi.getter(name="deleteUntagged")
    def delete_untagged(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Allow garbage collection on untagged artifacts.
        """
        return pulumi.get(self, "delete_untagged")

    @delete_untagged.setter
    def delete_untagged(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "delete_untagged", value)

    @_builtins.property
    @pulumi.getter
    def workers(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        return pulumi.get(self, "workers")

    @workers.setter
    def workers(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "workers", value)


@pulumi.input_type
class _GarbageCollectionState:
    def __init__(__self__, *,
                 delete_untagged: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 workers: pulumi.Input[Optional[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering GarbageCollection resources.

        :param pulumi.Input[_builtins.bool] delete_untagged: Allow garbage collection on untagged artifacts.
        :param pulumi.Input[_builtins.str] schedule: Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        :param pulumi.Input[_builtins.int] workers: Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        if delete_untagged is not None:
            pulumi.set(__self__, "delete_untagged", delete_untagged)
        if schedule is not None:
            pulumi.set(__self__, "schedule", schedule)
        if workers is not None:
            pulumi.set(__self__, "workers", workers)

    @_builtins.property
    @pulumi.getter(name="deleteUntagged")
    def delete_untagged(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Allow garbage collection on untagged artifacts.
        """
        return pulumi.get(self, "delete_untagged")

    @delete_untagged.setter
    def delete_untagged(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "delete_untagged", value)

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        """
        return pulumi.get(self, "schedule")

    @schedule.setter
    def schedule(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schedule", value)

    @_builtins.property
    @pulumi.getter
    def workers(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        return pulumi.get(self, "workers")

    @workers.setter
    def workers(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "workers", value)


@pulumi.type_token("harbor:index/garbageCollection:GarbageCollection")
class GarbageCollection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 delete_untagged: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 workers: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        ## Example Usage


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] delete_untagged: Allow garbage collection on untagged artifacts.
        :param pulumi.Input[_builtins.str] schedule: Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        :param pulumi.Input[_builtins.int] workers: Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GarbageCollectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage


        :param str resource_name: The name of the resource.
        :param GarbageCollectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GarbageCollectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 delete_untagged: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 workers: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GarbageCollectionArgs.__new__(GarbageCollectionArgs)

            __props__.__dict__["delete_untagged"] = delete_untagged
            if schedule is None and not opts.urn:
                raise TypeError("Missing required property 'schedule'")
            __props__.__dict__["schedule"] = schedule
            __props__.__dict__["workers"] = workers
        super(GarbageCollection, __self__).__init__(
            'harbor:index/garbageCollection:GarbageCollection',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            delete_untagged: pulumi.Input[Optional[_builtins.bool]] = None,
            schedule: pulumi.Input[Optional[_builtins.str]] = None,
            workers: pulumi.Input[Optional[_builtins.int]] = None) -> 'GarbageCollection':
        """
        Get an existing GarbageCollection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] delete_untagged: Allow garbage collection on untagged artifacts.
        :param pulumi.Input[_builtins.str] schedule: Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        :param pulumi.Input[_builtins.int] workers: Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GarbageCollectionState.__new__(_GarbageCollectionState)

        __props__.__dict__["delete_untagged"] = delete_untagged
        __props__.__dict__["schedule"] = schedule
        __props__.__dict__["workers"] = workers
        return GarbageCollection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="deleteUntagged")
    def delete_untagged(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Allow garbage collection on untagged artifacts.
        """
        return pulumi.get(self, "delete_untagged")

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Output[_builtins.str]:
        """
        Sets the schedule how often the Garbage Collection will run.  Can be to `"hourly"`, `"daily"`, `"weekly"` or can be a custom cron string ie, `"0 5 4 * * *"`
        """
        return pulumi.get(self, "schedule")

    @_builtins.property
    @pulumi.getter
    def workers(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Number of workers to run the garbage collection, value must be greater than or equal to one. Harbor limits the number of concurrent workers internally, setting this value higher than what Harbor supports will result in an error.
        """
        return pulumi.get(self, "workers")

