// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConfigSystemBannerMessageArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConfigSystemBannerMessageArgs Empty = new ConfigSystemBannerMessageArgs();

    /**
     * Whether or not the banner message is closable.
     * 
     */
    @Import(name="closable")
    private @Nullable Output<Boolean> closable;

    /**
     * @return Whether or not the banner message is closable.
     * 
     */
    public Optional<Output<Boolean>> closable() {
        return Optional.ofNullable(this.closable);
    }

    /**
     * The date the banner message will start displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    @Import(name="fromDate")
    private @Nullable Output<String> fromDate;

    /**
     * @return The date the banner message will start displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    public Optional<Output<String>> fromDate() {
        return Optional.ofNullable(this.fromDate);
    }

    /**
     * The message to display in the banner.
     * 
     */
    @Import(name="message", required=true)
    private Output<String> message;

    /**
     * @return The message to display in the banner.
     * 
     */
    public Output<String> message() {
        return this.message;
    }

    /**
     * The date the banner message will stop displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    @Import(name="toDate")
    private @Nullable Output<String> toDate;

    /**
     * @return The date the banner message will stop displaying. (Format: `MM/DD/YYYY`)
     * 
     */
    public Optional<Output<String>> toDate() {
        return Optional.ofNullable(this.toDate);
    }

    /**
     * The type of banner message. Can be `&#34;info&#34;`, `&#34;warning&#34;`, `&#34;success&#34;` or `&#34;danger&#34;`.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return The type of banner message. Can be `&#34;info&#34;`, `&#34;warning&#34;`, `&#34;success&#34;` or `&#34;danger&#34;`.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private ConfigSystemBannerMessageArgs() {}

    private ConfigSystemBannerMessageArgs(ConfigSystemBannerMessageArgs $) {
        this.closable = $.closable;
        this.fromDate = $.fromDate;
        this.message = $.message;
        this.toDate = $.toDate;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConfigSystemBannerMessageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConfigSystemBannerMessageArgs $;

        public Builder() {
            $ = new ConfigSystemBannerMessageArgs();
        }

        public Builder(ConfigSystemBannerMessageArgs defaults) {
            $ = new ConfigSystemBannerMessageArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param closable Whether or not the banner message is closable.
         * 
         * @return builder
         * 
         */
        public Builder closable(@Nullable Output<Boolean> closable) {
            $.closable = closable;
            return this;
        }

        /**
         * @param closable Whether or not the banner message is closable.
         * 
         * @return builder
         * 
         */
        public Builder closable(Boolean closable) {
            return closable(Output.of(closable));
        }

        /**
         * @param fromDate The date the banner message will start displaying. (Format: `MM/DD/YYYY`)
         * 
         * @return builder
         * 
         */
        public Builder fromDate(@Nullable Output<String> fromDate) {
            $.fromDate = fromDate;
            return this;
        }

        /**
         * @param fromDate The date the banner message will start displaying. (Format: `MM/DD/YYYY`)
         * 
         * @return builder
         * 
         */
        public Builder fromDate(String fromDate) {
            return fromDate(Output.of(fromDate));
        }

        /**
         * @param message The message to display in the banner.
         * 
         * @return builder
         * 
         */
        public Builder message(Output<String> message) {
            $.message = message;
            return this;
        }

        /**
         * @param message The message to display in the banner.
         * 
         * @return builder
         * 
         */
        public Builder message(String message) {
            return message(Output.of(message));
        }

        /**
         * @param toDate The date the banner message will stop displaying. (Format: `MM/DD/YYYY`)
         * 
         * @return builder
         * 
         */
        public Builder toDate(@Nullable Output<String> toDate) {
            $.toDate = toDate;
            return this;
        }

        /**
         * @param toDate The date the banner message will stop displaying. (Format: `MM/DD/YYYY`)
         * 
         * @return builder
         * 
         */
        public Builder toDate(String toDate) {
            return toDate(Output.of(toDate));
        }

        /**
         * @param type The type of banner message. Can be `&#34;info&#34;`, `&#34;warning&#34;`, `&#34;success&#34;` or `&#34;danger&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of banner message. Can be `&#34;info&#34;`, `&#34;warning&#34;`, `&#34;success&#34;` or `&#34;danger&#34;`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ConfigSystemBannerMessageArgs build() {
            if ($.message == null) {
                throw new MissingRequiredPropertyException("ConfigSystemBannerMessageArgs", "message");
            }
            return $;
        }
    }

}
