// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConfigSecurityState extends com.pulumi.resources.ResourceArgs {

    public static final ConfigSecurityState Empty = new ConfigSecurityState();

    /**
     * Time of creation of the list.
     * 
     */
    @Import(name="creationTime")
    private @Nullable Output<String> creationTime;

    /**
     * @return Time of creation of the list.
     * 
     */
    public Optional<Output<String>> creationTime() {
        return Optional.ofNullable(this.creationTime);
    }

    /**
     * System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `[&#34;CVE-123&#34;, &#34;CVE-145&#34;]` or `[&#34;CVE-123&#34;]`
     * 
     */
    @Import(name="cveAllowlists")
    private @Nullable Output<List<String>> cveAllowlists;

    /**
     * @return System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `[&#34;CVE-123&#34;, &#34;CVE-145&#34;]` or `[&#34;CVE-123&#34;]`
     * 
     */
    public Optional<Output<List<String>>> cveAllowlists() {
        return Optional.ofNullable(this.cveAllowlists);
    }

    /**
     * The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it&#39;s not set the CVE allowlist does not expire.
     * 
     */
    @Import(name="expiresAt")
    private @Nullable Output<Integer> expiresAt;

    /**
     * @return The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it&#39;s not set the CVE allowlist does not expire.
     * 
     */
    public Optional<Output<Integer>> expiresAt() {
        return Optional.ofNullable(this.expiresAt);
    }

    /**
     * Time of update of the list.
     * 
     */
    @Import(name="updateTime")
    private @Nullable Output<String> updateTime;

    /**
     * @return Time of update of the list.
     * 
     */
    public Optional<Output<String>> updateTime() {
        return Optional.ofNullable(this.updateTime);
    }

    private ConfigSecurityState() {}

    private ConfigSecurityState(ConfigSecurityState $) {
        this.creationTime = $.creationTime;
        this.cveAllowlists = $.cveAllowlists;
        this.expiresAt = $.expiresAt;
        this.updateTime = $.updateTime;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConfigSecurityState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConfigSecurityState $;

        public Builder() {
            $ = new ConfigSecurityState();
        }

        public Builder(ConfigSecurityState defaults) {
            $ = new ConfigSecurityState(Objects.requireNonNull(defaults));
        }

        /**
         * @param creationTime Time of creation of the list.
         * 
         * @return builder
         * 
         */
        public Builder creationTime(@Nullable Output<String> creationTime) {
            $.creationTime = creationTime;
            return this;
        }

        /**
         * @param creationTime Time of creation of the list.
         * 
         * @return builder
         * 
         */
        public Builder creationTime(String creationTime) {
            return creationTime(Output.of(creationTime));
        }

        /**
         * @param cveAllowlists System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `[&#34;CVE-123&#34;, &#34;CVE-145&#34;]` or `[&#34;CVE-123&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder cveAllowlists(@Nullable Output<List<String>> cveAllowlists) {
            $.cveAllowlists = cveAllowlists;
            return this;
        }

        /**
         * @param cveAllowlists System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `[&#34;CVE-123&#34;, &#34;CVE-145&#34;]` or `[&#34;CVE-123&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder cveAllowlists(List<String> cveAllowlists) {
            return cveAllowlists(Output.of(cveAllowlists));
        }

        /**
         * @param cveAllowlists System allowlist. Vulnerabilities in this list will be ignored when pushing and pulling images. Should be in the format or `[&#34;CVE-123&#34;, &#34;CVE-145&#34;]` or `[&#34;CVE-123&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder cveAllowlists(String... cveAllowlists) {
            return cveAllowlists(List.of(cveAllowlists));
        }

        /**
         * @param expiresAt The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it&#39;s not set the CVE allowlist does not expire.
         * 
         * @return builder
         * 
         */
        public Builder expiresAt(@Nullable Output<Integer> expiresAt) {
            $.expiresAt = expiresAt;
            return this;
        }

        /**
         * @param expiresAt The time for expiration of the allowlist, in the form of seconds since epoch. This is an optional attribute, if it&#39;s not set the CVE allowlist does not expire.
         * 
         * @return builder
         * 
         */
        public Builder expiresAt(Integer expiresAt) {
            return expiresAt(Output.of(expiresAt));
        }

        /**
         * @param updateTime Time of update of the list.
         * 
         * @return builder
         * 
         */
        public Builder updateTime(@Nullable Output<String> updateTime) {
            $.updateTime = updateTime;
            return this;
        }

        /**
         * @param updateTime Time of update of the list.
         * 
         * @return builder
         * 
         */
        public Builder updateTime(String updateTime) {
            return updateTime(Output.of(updateTime));
        }

        public ConfigSecurityState build() {
            return $;
        }
    }

}
