// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetProjectMemberGroupsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetProjectMemberGroupsPlainArgs Empty = new GetProjectMemberGroupsPlainArgs();

    /**
     * The id of the project within harbor.
     * 
     */
    @Import(name="projectId", required=true)
    private String projectId;

    /**
     * @return The id of the project within harbor.
     * 
     */
    public String projectId() {
        return this.projectId;
    }

    private GetProjectMemberGroupsPlainArgs() {}

    private GetProjectMemberGroupsPlainArgs(GetProjectMemberGroupsPlainArgs $) {
        this.projectId = $.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProjectMemberGroupsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProjectMemberGroupsPlainArgs $;

        public Builder() {
            $ = new GetProjectMemberGroupsPlainArgs();
        }

        public Builder(GetProjectMemberGroupsPlainArgs defaults) {
            $ = new GetProjectMemberGroupsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param projectId The id of the project within harbor.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            $.projectId = projectId;
            return this;
        }

        public GetProjectMemberGroupsPlainArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetProjectMemberGroupsPlainArgs", "projectId");
            }
            return $;
        }
    }

}
