// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumiverse.harbor.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetProjectsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetProjectsArgs Empty = new GetProjectsArgs();

    /**
     * The name of the project.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the project.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * If the project has public accessibility.
     * 
     */
    @Import(name="public")
    private @Nullable Output<Boolean> public_;

    /**
     * @return If the project has public accessibility.
     * 
     */
    public Optional<Output<Boolean>> public_() {
        return Optional.ofNullable(this.public_);
    }

    /**
     * The type of the project : Project or ProxyCache.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return The type of the project : Project or ProxyCache.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * If the images will be scanned for vulnerabilities when push to harbor.
     * 
     */
    @Import(name="vulnerabilityScanning")
    private @Nullable Output<Boolean> vulnerabilityScanning;

    /**
     * @return If the images will be scanned for vulnerabilities when push to harbor.
     * 
     */
    public Optional<Output<Boolean>> vulnerabilityScanning() {
        return Optional.ofNullable(this.vulnerabilityScanning);
    }

    private GetProjectsArgs() {}

    private GetProjectsArgs(GetProjectsArgs $) {
        this.name = $.name;
        this.public_ = $.public_;
        this.type = $.type;
        this.vulnerabilityScanning = $.vulnerabilityScanning;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProjectsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProjectsArgs $;

        public Builder() {
            $ = new GetProjectsArgs();
        }

        public Builder(GetProjectsArgs defaults) {
            $ = new GetProjectsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the project.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the project.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param public_ If the project has public accessibility.
         * 
         * @return builder
         * 
         */
        public Builder public_(@Nullable Output<Boolean> public_) {
            $.public_ = public_;
            return this;
        }

        /**
         * @param public_ If the project has public accessibility.
         * 
         * @return builder
         * 
         */
        public Builder public_(Boolean public_) {
            return public_(Output.of(public_));
        }

        /**
         * @param type The type of the project : Project or ProxyCache.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of the project : Project or ProxyCache.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param vulnerabilityScanning If the images will be scanned for vulnerabilities when push to harbor.
         * 
         * @return builder
         * 
         */
        public Builder vulnerabilityScanning(@Nullable Output<Boolean> vulnerabilityScanning) {
            $.vulnerabilityScanning = vulnerabilityScanning;
            return this;
        }

        /**
         * @param vulnerabilityScanning If the images will be scanned for vulnerabilities when push to harbor.
         * 
         * @return builder
         * 
         */
        public Builder vulnerabilityScanning(Boolean vulnerabilityScanning) {
            return vulnerabilityScanning(Output.of(vulnerabilityScanning));
        }

        public GetProjectsArgs build() {
            return $;
        }
    }

}
