// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Harbor.Inputs
{

    public sealed class RobotAccountPermissionAccessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Eg. `Push`, `Pull`, `Read`, etc. Check [available actions](https://github.com/goharbor/harbor/blob/-/src/common/rbac/const.go).
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        /// <summary>
        /// Either `Allow` or `Deny`. Defaults to `Allow`.
        /// </summary>
        [Input("effect")]
        public Input<string>? Effect { get; set; }

        /// <summary>
        /// Eg. `Repository`, `Labels`, etc. Check [available resources](https://github.com/goharbor/harbor/blob/-/src/common/rbac/const.go).
        /// </summary>
        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        public RobotAccountPermissionAccessArgs()
        {
        }
        public static new RobotAccountPermissionAccessArgs Empty => new RobotAccountPermissionAccessArgs();
    }
}
