// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import harbor:index/replication:Replication main /replication/policies/1
 * ```
 */
export class Replication extends pulumi.CustomResource {
    /**
     * Get an existing Replication resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ReplicationState, opts?: pulumi.CustomResourceOptions): Replication {
        return new Replication(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'harbor:index/replication:Replication';

    /**
     * Returns true if the given object is an instance of Replication.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Replication {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Replication.__pulumiType;
    }

    declare public readonly action: pulumi.Output<string>;
    /**
     * Specify whether to enable the artifact blobs copied by chunks. (Default: `false`)
     */
    declare public readonly copyByChunk: pulumi.Output<boolean | undefined>;
    /**
     * Specify whether to delete the remote resources when locally deleted. (Default: `false`)
     */
    declare public readonly deletion: pulumi.Output<boolean | undefined>;
    /**
     * Description of the replication policy.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Specify the destination namespace. if empty, the resource will be put under the same namespace as the source.
     */
    declare public readonly destNamespace: pulumi.Output<string | undefined>;
    /**
     * Specify the destination namespace flattening policy. Integers from `-1` to `3` are valid values in the harbor API. A value of `-1` will 'Flatten All Levels', `0` means 'No Flattening', `1` 'Flatten 1 Level', `2` 'Flatten 2 Levels', `3` 'Flatten 3 Levels' (Default: `0`, see [Replication Rules](https://goharbor.io/docs/latest/administration/configuring-replication/create-replication-rules/) for more details)
     */
    declare public readonly destNamespaceReplace: pulumi.Output<number | undefined>;
    /**
     * Specify whether the replication is enabled. (Default: `true`)
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * Specify whether to execute the replication rule if new or modified. (Default: `false`)
     */
    declare public readonly executeOnChanged: pulumi.Output<boolean | undefined>;
    declare public readonly filters: pulumi.Output<outputs.ReplicationFilter[] | undefined>;
    /**
     * The name of the replication.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Specify whether to override the resources at the destination if a resources with the same name exist. (Default: `true`)
     */
    declare public readonly override: pulumi.Output<boolean | undefined>;
    /**
     * The registry ID of the Registry Endpoint.
     */
    declare public readonly registryId: pulumi.Output<number>;
    declare public /*out*/ readonly replicationPolicyId: pulumi.Output<number>;
    /**
     * The scheduled time of when the container register will be push / pull. In cron base format. Hourly `"0 0 * * * *"`, Daily `"0 0 0 * * *"`, Monthly `"0 0 0 * * 0"`. Can be one of the following: `eventBased`, `manual`, `cron format` (Default: `manual`)
     */
    declare public readonly schedule: pulumi.Output<string | undefined>;
    /**
     * , prevent parallel runs under the same replication. (Default: `false`)
     */
    declare public readonly singleActiveReplication: pulumi.Output<boolean | undefined>;
    /**
     * The Maximum network bandwidth in Kbps for each execution. Default is `-1` (unlimited).
     */
    declare public readonly speed: pulumi.Output<number | undefined>;

    /**
     * Create a Replication resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ReplicationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ReplicationArgs | ReplicationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ReplicationState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["copyByChunk"] = state?.copyByChunk;
            resourceInputs["deletion"] = state?.deletion;
            resourceInputs["description"] = state?.description;
            resourceInputs["destNamespace"] = state?.destNamespace;
            resourceInputs["destNamespaceReplace"] = state?.destNamespaceReplace;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["executeOnChanged"] = state?.executeOnChanged;
            resourceInputs["filters"] = state?.filters;
            resourceInputs["name"] = state?.name;
            resourceInputs["override"] = state?.override;
            resourceInputs["registryId"] = state?.registryId;
            resourceInputs["replicationPolicyId"] = state?.replicationPolicyId;
            resourceInputs["schedule"] = state?.schedule;
            resourceInputs["singleActiveReplication"] = state?.singleActiveReplication;
            resourceInputs["speed"] = state?.speed;
        } else {
            const args = argsOrState as ReplicationArgs | undefined;
            if (args?.action === undefined && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if (args?.registryId === undefined && !opts.urn) {
                throw new Error("Missing required property 'registryId'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["copyByChunk"] = args?.copyByChunk;
            resourceInputs["deletion"] = args?.deletion;
            resourceInputs["description"] = args?.description;
            resourceInputs["destNamespace"] = args?.destNamespace;
            resourceInputs["destNamespaceReplace"] = args?.destNamespaceReplace;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["executeOnChanged"] = args?.executeOnChanged;
            resourceInputs["filters"] = args?.filters;
            resourceInputs["name"] = args?.name;
            resourceInputs["override"] = args?.override;
            resourceInputs["registryId"] = args?.registryId;
            resourceInputs["schedule"] = args?.schedule;
            resourceInputs["singleActiveReplication"] = args?.singleActiveReplication;
            resourceInputs["speed"] = args?.speed;
            resourceInputs["replicationPolicyId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Replication.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Replication resources.
 */
export interface ReplicationState {
    action?: pulumi.Input<string | undefined>;
    /**
     * Specify whether to enable the artifact blobs copied by chunks. (Default: `false`)
     */
    copyByChunk?: pulumi.Input<boolean | undefined>;
    /**
     * Specify whether to delete the remote resources when locally deleted. (Default: `false`)
     */
    deletion?: pulumi.Input<boolean | undefined>;
    /**
     * Description of the replication policy.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Specify the destination namespace. if empty, the resource will be put under the same namespace as the source.
     */
    destNamespace?: pulumi.Input<string | undefined>;
    /**
     * Specify the destination namespace flattening policy. Integers from `-1` to `3` are valid values in the harbor API. A value of `-1` will 'Flatten All Levels', `0` means 'No Flattening', `1` 'Flatten 1 Level', `2` 'Flatten 2 Levels', `3` 'Flatten 3 Levels' (Default: `0`, see [Replication Rules](https://goharbor.io/docs/latest/administration/configuring-replication/create-replication-rules/) for more details)
     */
    destNamespaceReplace?: pulumi.Input<number | undefined>;
    /**
     * Specify whether the replication is enabled. (Default: `true`)
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Specify whether to execute the replication rule if new or modified. (Default: `false`)
     */
    executeOnChanged?: pulumi.Input<boolean | undefined>;
    filters?: pulumi.Input<pulumi.Input<inputs.ReplicationFilter>[] | undefined>;
    /**
     * The name of the replication.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Specify whether to override the resources at the destination if a resources with the same name exist. (Default: `true`)
     */
    override?: pulumi.Input<boolean | undefined>;
    /**
     * The registry ID of the Registry Endpoint.
     */
    registryId?: pulumi.Input<number | undefined>;
    replicationPolicyId?: pulumi.Input<number | undefined>;
    /**
     * The scheduled time of when the container register will be push / pull. In cron base format. Hourly `"0 0 * * * *"`, Daily `"0 0 0 * * *"`, Monthly `"0 0 0 * * 0"`. Can be one of the following: `eventBased`, `manual`, `cron format` (Default: `manual`)
     */
    schedule?: pulumi.Input<string | undefined>;
    /**
     * , prevent parallel runs under the same replication. (Default: `false`)
     */
    singleActiveReplication?: pulumi.Input<boolean | undefined>;
    /**
     * The Maximum network bandwidth in Kbps for each execution. Default is `-1` (unlimited).
     */
    speed?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Replication resource.
 */
export interface ReplicationArgs {
    action: pulumi.Input<string>;
    /**
     * Specify whether to enable the artifact blobs copied by chunks. (Default: `false`)
     */
    copyByChunk?: pulumi.Input<boolean | undefined>;
    /**
     * Specify whether to delete the remote resources when locally deleted. (Default: `false`)
     */
    deletion?: pulumi.Input<boolean | undefined>;
    /**
     * Description of the replication policy.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Specify the destination namespace. if empty, the resource will be put under the same namespace as the source.
     */
    destNamespace?: pulumi.Input<string | undefined>;
    /**
     * Specify the destination namespace flattening policy. Integers from `-1` to `3` are valid values in the harbor API. A value of `-1` will 'Flatten All Levels', `0` means 'No Flattening', `1` 'Flatten 1 Level', `2` 'Flatten 2 Levels', `3` 'Flatten 3 Levels' (Default: `0`, see [Replication Rules](https://goharbor.io/docs/latest/administration/configuring-replication/create-replication-rules/) for more details)
     */
    destNamespaceReplace?: pulumi.Input<number | undefined>;
    /**
     * Specify whether the replication is enabled. (Default: `true`)
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Specify whether to execute the replication rule if new or modified. (Default: `false`)
     */
    executeOnChanged?: pulumi.Input<boolean | undefined>;
    filters?: pulumi.Input<pulumi.Input<inputs.ReplicationFilter>[] | undefined>;
    /**
     * The name of the replication.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Specify whether to override the resources at the destination if a resources with the same name exist. (Default: `true`)
     */
    override?: pulumi.Input<boolean | undefined>;
    /**
     * The registry ID of the Registry Endpoint.
     */
    registryId: pulumi.Input<number>;
    /**
     * The scheduled time of when the container register will be push / pull. In cron base format. Hourly `"0 0 * * * *"`, Daily `"0 0 0 * * *"`, Monthly `"0 0 0 * * 0"`. Can be one of the following: `eventBased`, `manual`, `cron format` (Default: `manual`)
     */
    schedule?: pulumi.Input<string | undefined>;
    /**
     * , prevent parallel runs under the same replication. (Default: `false`)
     */
    singleActiveReplication?: pulumi.Input<boolean | undefined>;
    /**
     * The Maximum network bandwidth in Kbps for each execution. Default is `-1` (unlimited).
     */
    speed?: pulumi.Input<number | undefined>;
}
