// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ### System Level
 * Introduced in harbor 2.2.0, system level robot accounts can have basically [all available permissions](https://github.com/goharbor/harbor/blob/-/src/common/rbac/const.go) in harbor and are not dependent on a single project.
 *
 * ### Global
 *
 * The above example, creates a system level robot account with permissions to
 * - permission to create labels on system level
 * - pull repository across all projects
 * - push repository to project "my-project-name"
 *
 * ### Project
 *
 * Other than system level robot accounts, project level robot accounts can interact on project level only.
 * The [available permissions](https://github.com/goharbor/harbor/blob/-/src/common/rbac/const.go) are mostly the same as for system level robots.
 *
 * ### Project with Write-only Secret
 *
 * ### Project with Write-only Secret from Ephemeral Random Secret
 *
 * The above example creates a project level robot account with permissions to
 * - pull repository on project "main"
 * - push repository on project "main"
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import harbor:index/robotAccount:RobotAccount system /robots/123
 * ```
 */
export class RobotAccount extends pulumi.CustomResource {
    /**
     * Get an existing RobotAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RobotAccountState, opts?: pulumi.CustomResourceOptions): RobotAccount {
        return new RobotAccount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'harbor:index/robotAccount:RobotAccount';

    /**
     * Returns true if the given object is an instance of RobotAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RobotAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RobotAccount.__pulumiType;
    }

    /**
     * The description of the robot account will be displayed in harbor.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Disables the robot account when set to `true`.
     */
    declare public readonly disable: pulumi.Output<boolean | undefined>;
    /**
     * By default, the robot account will not expire. Set it to the amount of days until the account should expire.
     */
    declare public readonly duration: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly fullName: pulumi.Output<string>;
    /**
     * Level of the robot account, currently either `system` or `project`.
     */
    declare public readonly level: pulumi.Output<string>;
    /**
     * The name of the project that will be created in harbor.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly permissions: pulumi.Output<outputs.RobotAccountPermission[]>;
    declare public /*out*/ readonly robotId: pulumi.Output<string>;
    /**
     * The secret of the robot account used for authentication. Defaults to random generated string from Harbor.
     */
    declare public readonly secret: pulumi.Output<string>;
    /**
     * Rotation trigger for write-only secret updates. Must be used together with `secretWo`.
     */
    declare public readonly secretWoVersion: pulumi.Output<number | undefined>;

    /**
     * Create a RobotAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RobotAccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RobotAccountArgs | RobotAccountState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RobotAccountState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["disable"] = state?.disable;
            resourceInputs["duration"] = state?.duration;
            resourceInputs["fullName"] = state?.fullName;
            resourceInputs["level"] = state?.level;
            resourceInputs["name"] = state?.name;
            resourceInputs["permissions"] = state?.permissions;
            resourceInputs["robotId"] = state?.robotId;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["secretWoVersion"] = state?.secretWoVersion;
        } else {
            const args = argsOrState as RobotAccountArgs | undefined;
            if (args?.level === undefined && !opts.urn) {
                throw new Error("Missing required property 'level'");
            }
            if (args?.permissions === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["disable"] = args?.disable;
            resourceInputs["duration"] = args?.duration;
            resourceInputs["level"] = args?.level;
            resourceInputs["name"] = args?.name;
            resourceInputs["permissions"] = args?.permissions;
            resourceInputs["secret"] = args?.secret ? pulumi.secret(args.secret) : undefined;
            resourceInputs["secretWoVersion"] = args?.secretWoVersion;
            resourceInputs["fullName"] = undefined /*out*/;
            resourceInputs["robotId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RobotAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RobotAccount resources.
 */
export interface RobotAccountState {
    /**
     * The description of the robot account will be displayed in harbor.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Disables the robot account when set to `true`.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * By default, the robot account will not expire. Set it to the amount of days until the account should expire.
     */
    duration?: pulumi.Input<number | undefined>;
    fullName?: pulumi.Input<string | undefined>;
    /**
     * Level of the robot account, currently either `system` or `project`.
     */
    level?: pulumi.Input<string | undefined>;
    /**
     * The name of the project that will be created in harbor.
     */
    name?: pulumi.Input<string | undefined>;
    permissions?: pulumi.Input<pulumi.Input<inputs.RobotAccountPermission>[] | undefined>;
    robotId?: pulumi.Input<string | undefined>;
    /**
     * The secret of the robot account used for authentication. Defaults to random generated string from Harbor.
     */
    secret?: pulumi.Input<string | undefined>;
    /**
     * Rotation trigger for write-only secret updates. Must be used together with `secretWo`.
     */
    secretWoVersion?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a RobotAccount resource.
 */
export interface RobotAccountArgs {
    /**
     * The description of the robot account will be displayed in harbor.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Disables the robot account when set to `true`.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * By default, the robot account will not expire. Set it to the amount of days until the account should expire.
     */
    duration?: pulumi.Input<number | undefined>;
    /**
     * Level of the robot account, currently either `system` or `project`.
     */
    level: pulumi.Input<string>;
    /**
     * The name of the project that will be created in harbor.
     */
    name?: pulumi.Input<string | undefined>;
    permissions: pulumi.Input<pulumi.Input<inputs.RobotAccountPermission>[]>;
    /**
     * The secret of the robot account used for authentication. Defaults to random generated string from Harbor.
     */
    secret?: pulumi.Input<string | undefined>;
    /**
     * Rotation trigger for write-only secret updates. Must be used together with `secretWo`.
     */
    secretWoVersion?: pulumi.Input<number | undefined>;
}
