// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ### Write-only Password
 *
 * ### Write-only Password from Ephemeral Random Secret
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import harbor:index/user:User main /users/19
 * ```
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'harbor:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * If the user will have admin rights within Harbor (Default: `false`)
     */
    declare public readonly admin: pulumi.Output<boolean | undefined>;
    /**
     * Any comments for that are need for the internal user.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The email address of the internal user.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * The Full Name of the internal user.
     */
    declare public readonly fullName: pulumi.Output<string>;
    /**
     * The password for the internal user. Conflicts with `passwordWoVersion`.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative for `password`. Must be used together with `passwordWoVersion`.
     */
    declare public readonly passwordWo: pulumi.Output<string | undefined>;
    /**
     * Rotation trigger for write-only password updates. Must be used together with `passwordWo`.
     */
    declare public readonly passwordWoVersion: pulumi.Output<number | undefined>;
    /**
     * The username of the internal user.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["admin"] = state?.admin;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["email"] = state?.email;
            resourceInputs["fullName"] = state?.fullName;
            resourceInputs["password"] = state?.password;
            resourceInputs["passwordWo"] = state?.passwordWo;
            resourceInputs["passwordWoVersion"] = state?.passwordWoVersion;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.fullName === undefined && !opts.urn) {
                throw new Error("Missing required property 'fullName'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["admin"] = args?.admin;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["email"] = args?.email;
            resourceInputs["fullName"] = args?.fullName;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["passwordWo"] = args?.passwordWo ? pulumi.secret(args.passwordWo) : undefined;
            resourceInputs["passwordWoVersion"] = args?.passwordWoVersion;
            resourceInputs["username"] = args?.username;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "passwordWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * If the user will have admin rights within Harbor (Default: `false`)
     */
    admin?: pulumi.Input<boolean | undefined>;
    /**
     * Any comments for that are need for the internal user.
     */
    comment?: pulumi.Input<string | undefined>;
    /**
     * The email address of the internal user.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * The Full Name of the internal user.
     */
    fullName?: pulumi.Input<string | undefined>;
    /**
     * The password for the internal user. Conflicts with `passwordWoVersion`.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative for `password`. Must be used together with `passwordWoVersion`.
     */
    passwordWo?: pulumi.Input<string | undefined>;
    /**
     * Rotation trigger for write-only password updates. Must be used together with `passwordWo`.
     */
    passwordWoVersion?: pulumi.Input<number | undefined>;
    /**
     * The username of the internal user.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * If the user will have admin rights within Harbor (Default: `false`)
     */
    admin?: pulumi.Input<boolean | undefined>;
    /**
     * Any comments for that are need for the internal user.
     */
    comment?: pulumi.Input<string | undefined>;
    /**
     * The email address of the internal user.
     */
    email: pulumi.Input<string>;
    /**
     * The Full Name of the internal user.
     */
    fullName: pulumi.Input<string>;
    /**
     * The password for the internal user. Conflicts with `passwordWoVersion`.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative for `password`. Must be used together with `passwordWoVersion`.
     */
    passwordWo?: pulumi.Input<string | undefined>;
    /**
     * Rotation trigger for write-only password updates. Must be used together with `passwordWo`.
     */
    passwordWoVersion?: pulumi.Input<number | undefined>;
    /**
     * The username of the internal user.
     */
    username: pulumi.Input<string>;
}
